### ISSUE TITLE
Connecting to existing Fluent session, password?

### ISSUE THREAD

**Issue by hanchak** [pyansys/pyfluent#1032]
### Discussed in https://github.com/pyansys/pyfluent/discussions/1031

<div type='discussions-op-text'>

<sup>Originally posted by **hanchak** October 21, 2022</sup>
I used the following to try to connect to my existing Fluent session:

`solver = pyfluent.launch_fluent(start_instance=False, ip='127.0.0.1', port='1055')`

I received the following error:

`RuntimeError: Fluent session password mismatch`

Is there a default password to connect to Fluent? I am connecting to my local Fluent on my machine, windows 10.

Thanks,
Mike</div>

**Comment by dnwillia-work** [comment]
There's a related issue for this already as well.  #229.

**Comment by hanchak** [comment]
Sorry for missing the previous issue. Also, thanks for your help.

Thing is... I am launching Fluent through he Workbench interface, so I have no launch options (other than # cores, IP, etc.)

I will look for a session file and search the Ansys knowledge base too.

**Comment by dnwillia-work** [comment]
The issues list is already quite long, no problem.

I'm not entirely certain what you might mean by launching Fluent through the Workbench interface as it does not support Python or PyFluent (we've certainly not tested that here at Ansys).

**Comment by hanchak** [comment]
Sorry for not being clear.  I use the Fluent workflow in Ansys Workbench. Import geometry, mesh, then launch fluent. Now, I am interested in connecting to that already existing Fluent session (say, for some parametric studies or to replace Journal files). Where would I look for the auto-generated password in order to get pyFluent connected?

**Comment by dnwillia-work** [comment]
Yeah, ok, I understand.

In order for that to work Workbench would need to start up Fluent with the `-sifile=<path>` argument passed to it.  I'm not sure if there is a way to pass Fluent additional command line arguments when you start it up in Workbench but if you could do that then you can add that argument and set the password/server file to be stored wherever you like.  eg:  `-sifile=c:\users\me\fluent-password.txt`.  Once Fluent is spun up you should be able to connect to it using PyFluent.

**Comment by hanchak** [comment]
Thanks, I'll give it a shot.  I will see if Fluent Launcher will accept additional arguments. If not, I will use pyFluent to launch fluent and load my case and data.

Thank you.
