### ISSUE TITLE
Bug in tests area module test_fix_doc.py

### ISSUE THREAD

**Issue by dnwillia-work** [pyansys/pyfluent#1051]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Tests won't run in VS Code because they depend on a module which is not installed from the `src` area.

### 📝 Steps to reproduce

Create a virtual environment with the modules and testing requirements installed.  i.e.
```
python -m venv venvtest
venvtest\Scripts\activate
pip install -e .
pip install -r requirements/requirements_tests.txt
```
activate that virtual environment in VS code (hit F1 and select Python:Select interpreter) and activate pytest (hit F1 and select Python:Configure Tests).

The testing view does not work because this testing module imports a module from `codegen` which is not included into the `src` area.

Pragmatic fix for now is to probably move the dependent code into `src`.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.4
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pyfluent.git@f609c765909d3ef8a595e80847c0402708109560#egg=ansys_fluent_core
ansys-platform-instancemanagement==1.0.2
appdirs==1.4.4
attrs==22.1.0
colorama==0.4.5
coverage==6.5.0
flake8==5.0.4
googleapis-common-protos==1.56.4
grpcio==1.50.0
h5py==3.7.0
importlib-metadata==5.0.0
iniconfig==1.1.1
mccabe==0.7.0
numpy==1.23.4
packaging==21.3
pandas==1.5.0
Pint==0.19.2
pluggy==1.0.0
protobuf==3.20.2
protoc-gen-swagger==0.1.0
psutil==5.9.2
py==1.11.0
pycodestyle==2.9.1
pyflakes==2.5.0
pyparsing==3.0.9
pytest==7.1.3
pytest-cov==4.0.0
pytest-mock==3.10.0
python-dateutil==2.8.2
pytz==2022.5
six==1.16.0
tomli==2.0.1
zipp==3.9.0
```

**Comment by mkundu1** [comment]
In github CI, we run pytest as `python -m pytest` which adds the current directory in Python module search path, but that won't work for running pytest from IDE GUIs.

I'll move the code to src.
