### ISSUE TITLE
Issue with the syntax in fluent meshing

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1058]
When I am trying to use the below command in pyfluent it is throwing invalid syntax
meshing.tui(tgapi-util-get-minsize-face-zone-by-area "origin*")

**Comment by pavankumarkonchada** [comment]
Please can any one look into this

**Comment by mkundu1** [comment]
As `tgapi-util-get-minsize-face-zone-by-area` is a scheme function, the scheme_eval API is most suitable for it:
```
>>> import ansys.fluent.core as pyfluent
>>> meshing = pyfluent.launch_fluent(mode="meshing", show_gui=True)
>>> meshing.tui.file.read_mesh("elbow.msh.h5")
>>> meshing.scheme_eval.scheme_eval('(tgapi-util-get-minsize-face-zone-by-area "*")')
30
```
