### ISSUE TITLE
PyTest configuration issue with VS code

### ISSUE THREAD

**Issue by akulshre-qa** [pyansys/pyfluent#1060]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

After @dnwillia pointed out some issues related to PyTest in VS code, I tried configuring it on the testing machine. We encountered that the configuration issue comes with the following errors:

![vscode_configError](https://user-images.githubusercontent.com/103188356/199806226-5adf69af-64ea-4e89-addf-389d30d1e2e9.png)

![vscode_configError_test2](https://user-images.githubusercontent.com/103188356/199806272-7c598ccd-e519-4ae6-8f09-cd945efaf810.png)

If I delete those two tests i.e. test_fluent_session.py and test_fix_doc.py, VS code works fine and it loads all the PyTests without any error. See below PyTest structure loaded successfully after deleting the above tests:
![vscode_working](https://user-images.githubusercontent.com/103188356/199806734-7ee671db-16ef-4381-8f60-36774cc3cb53.png)

We, therefore, should look at those two tests on why are they showing module import errors in order to make PyTest work in VS code. 

### 📝 Steps to reproduce

Open Pyfluent project in VS code, configure Python environment and try to load PyTests. 

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
python 3.8
```

**Comment by akulshre-qa** [comment]
@ypatel-qa @dnwillia FYI

**Comment by dnwillia-work** [comment]
I might have beat you to it for part of this #1051.

**Comment by akulshre-qa** [comment]
Thanks, @dnwillia-work
