### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1070]
meshing.tui.file.import.cad("yes",import_filename,"no","yes",40,"yes","mm")

   meshing.tui.file.import.cad("yes",import_filename,"no","yes",40,"yes","mm")
                     ^
SyntaxError: invalid syntax

**Comment by pavankumarkonchada** [comment]
It is throwing invalid syntax at import

**Comment by pavankumarkonchada** [comment]
Can any one help me

**Comment by mkundu1** [comment]
How are you running the commands? Is it from command prompt, any IDE?

Can you please also share the previous lines?

**Comment by pavankumarkonchada** [comment]
i am using jupyter notebook

**Comment by mkundu1** [comment]
Please input the filename as:
meshing.tui.file.import.cad("yes",r"E:/artery.stl","no","yes",40,"yes","mm")

https://stackoverflow.com/questions/2953834/windows-path-in-python

**Comment by pavankumarkonchada** [comment]
It is not working the above syntax also

**Comment by mkundu1** [comment]
Can you please share the screenshot of the error from jupyter notebook?

**Comment by pavankumarkonchada** [comment]
![image](https://user-images.githubusercontent.com/113668310/200296155-8b6ddde9-49fc-410e-9c1e-20223d95530b.png)

**Comment by mkundu1** [comment]
Now I see where the error is pointing at. In this case the path is `meshing.tui.file.import_.cad`.
```
>>> dir(meshing.tui.file)
['cff_files', 'confirm_overwrite', 'export', 'file_format', 'filter_list', 'filter_options', 'hdf_files', 'import_', 'load_act_tool', 'read_boundary_mesh', 'read_case', 'read_journal', 'read_mesh', 'read_meshes_by_tmerge', 'read_multi_bound_mesh', 'read_multiple_mesh', 'read_options', 'read_size_field', 'set_tui_version', 'show_configuration', 'start_journal', 'start_transcript']
```
We could not use `import` as it conflicts with python keyword.

**Comment by pavankumarkonchada** [comment]
Thank you its working
