### ISSUE TITLE
Syntax issue with diagnostics option

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1074]
meshing.tui.diagnostics.face_connectivity.fix_free_faces("objects","zone-solid",[],"merge-nodes",[],[])

_InactiveRpcError                         Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_17504\3656970885.py in <module>
----> 1 meshing.tui.diagnostics.face_connectivity.fix_free_faces.merge_nodes("","")

~\AppData\Roaming\Python\Python39\site-packages\ansys\fluent\core\session_meshing.py in tui(self)
     34         """Instance of ``main_menu`` on which Fluent's SolverTUI methods can be
     35         executed."""
---> 36         return super(Meshing, self).tui if not self.switched else None
     37 
     38     @property

~\AppData\Roaming\Python\Python39\site-packages\ansys\fluent\core\session_pure_meshing.py in tui(self)
     26         """Instance of ``main_menu`` on which Fluent's SolverTUI methods can be
     27         executed."""
---> 28         return self._base_meshing.tui
     29 
     30     @property

**Comment by pavankumarkonchada** [comment]
I have tried even this syntax but this too did not work out
meshing.tui.diagnostics.face_connectivity.quality.general_improve["Target objects/face-zones"].objects("zone-solid",[])["Quality Method"].skewness(0.9,30,5,"yes")

**Comment by mkundu1** [comment]
`meshing.tui.diagnostics.face_connectivity.fix_free_faces` is a valid command, but `meshing.tui.diagnostics.face_connectivity.fix_free_faces.merge_nodes`. It is not clear how the latter gets executed. Can you please share a screenshot?

**Comment by pavankumarkonchada** [comment]
![image](https://user-images.githubusercontent.com/113668310/200570347-c394d1d3-fce7-4fef-9c20-bcd77e426110.png)

**Comment by pavankumarkonchada** [comment]
this is how it is in fluent,please suggest me how to handle this kind of syntax

**Comment by pavankumarkonchada** [comment]
![image](https://user-images.githubusercontent.com/113668310/200578136-6efea880-b5d7-4efc-8f17-4cf3a35e7994.png)

**Comment by pavankumarkonchada** [comment]
This is how it is completely in fluent, waiting for your answer

**Comment by mkundu1** [comment]
`meshing.tui.diagnostics.face_connectivity.fix_free_faces("objects", "zone-solid", "()", "merge-nodes", "no", 7.056e-7)`

**Comment by pavankumarkonchada** [comment]
Thank you
