### ISSUE TITLE
Add cell zone data export function in FieldData API

### ISSUE THREAD

**Issue by yujiangsenior** [pyansys/pyfluent#1085]
### 📝 Description of the feature

Hi there,

With FieldData api, now we could get scalar or vector field from a surface or boundary, but how to export the scalar or vector field from a cell zone (e.g. the  fluid region in a 3D stirring tank) ? Is there any other way except FieldData api that could do this? If not, could FieldData api include such options for cell zone/domain information export... Thanks.

**Comment by dnwillia-work** [comment]
Hi, thanks for the feedback!  I have a few questions.

Do you need the volume mesh and field data?

If Fluent is running in parallel, with multiple compute nodes, would you need the data reorganized so that it's the serial order?

Do you need to write data back into Fluent?

**Comment by yujiangsenior** [comment]
Hi there, I just saw this reply. To address your questions, 1. Yes both volume mesh, field data are required, as well as the coordinates of each mesh/cell. 2. Yes the serial ordered solution is expected from my side, so that I could do 3. 3.After dealing with the data from fielddata API, the processed data are supposed to read back to Fluent to visualise, also it is supposed to be  visualised by pyfluent-visualisation.. 
Thanks so much for your consideration.

**Comment by yujiangsenior** [comment]
> Hi, thanks for the feedback! I have a few questions.
> 
> Do you need the volume mesh and field data?
> 
> If Fluent is running in parallel, with multiple compute nodes, would you need the data reorganized so that it's the serial order?
> 
> Do you need to write any data back into Fluent?

Hi, I replied last month but haven't seen response yet. Just want to check that is there any plans for adding this cell data access to this FieldData API? 

I mean if a 3D tank is simulated, how could I do some calculation on a specific field (e.g. Temperature) on the overall 3D fluid zone, and then visualize the new results (e.g. Temperature value in all the cells changed by the calculation) in the same mesh/geometry? Many thanks for helping.

**Comment by dnwillia-work** [comment]
Sorry for not replying sooner, thanks for clarifying the ask.  Normally one would use expressions and/or custom field functions or user defined memory for that sort of thing. These fields can be post processed using the Fluent post processing APIs.
