### ISSUE TITLE
The variable created is none type but wanted a real type

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1114]
inletx =solver.tui.report.surface_integrals.area_weighted_avg("inlet",[],"x-coordinate","no")

The inletx is none type, but wanted the xcoordinate in real type so that I can create a point

**Comment by pavankumarkonchada** [comment]
Please any one can help me here

**Comment by snallamoansys** [comment]
Hi @pavankumarkonchada, printed values from fluent console are not directly accessible. Please use this approach.

![image](https://user-images.githubusercontent.com/99287292/204468938-510aff84-f944-4615-8eab-8630bbf33577.png)
