### ISSUE TITLE
Turbulence Multiphase Model is not available/seen in the viscous model class

### ISSUE THREAD

**Issue by sujal-tipnis** [pyansys/pyfluent#112]
To reproduce:

- Start Fluent using pyfluent in 3ddp
- Read any 3d mesh file.
- Run the following script to enable the Eulerian multiphase model

_import ansys.fluent as pyfluent
import os
path = os.getcwd()
s= pyfluent.launch_fluent()
s.check_health()
s.tui.solver.file.show_configuration()
s.tui.solver.file.read_case(case_file_name=path + '/mesh_files/mixing_tank.msh')

root = s.get_settings_root()
s.tui.solver.define.operating_conditions.gravity("yes","0","0","-9.81")
s.tui.solver.define.operating_conditions.operating_density("yes", "1.225")

root.setup.models.multiphase.models = 'eulerian'_

Now when I print status of the viscous model, I do not see the Turbulence Multiphase Model options as seen below:

root.setup.models.viscous.print_state()
_model : k-omega-standard
options : 
  curvature_correction : False
  corner_flow_correction : False
  production_kato_launder : False
  production_limiter : True
k_omega_model : sst
k_omega_options : 
  kw_low_re_correction : False_

The subsequent Fluent GUI has the following options: 

![image](https://user-images.githubusercontent.com/97630067/156464225-6b5a76dc-3058-4651-9281-9b20f53b6773.png)

**Comment by seanpearsonuk** [comment]
In 231
