### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by gibbsycfd** [pyansys/pyfluent#1134]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![pyfluent gravity error](https://user-images.githubusercontent.com/119614403/205106465-83b75163-3a2c-405e-bb96-1cf6d10675da.jpg)

Attempting to set gravity to true but the command doesn't seem to recognise anything after root.setup.general, whether I try .gravity or .solver.

### 📝 Steps to reproduce

1. Launch solver session
2. Import .cas
3. attempt to set gravity to true using root.setup.general.gravity

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.5
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.11.0
ansys-platform-instancemanagement==1.0.2
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.0
attrs==22.1.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.6
comm==0.1.1
debugpy==1.6.4
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
googleapis-common-protos==1.56.4
grpcio==1.50.0
h5py==3.7.0
idna==3.4
importlib-metadata==5.1.0
ipykernel==6.18.2
ipython==8.7.0
ipython-genutils==0.2.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.10
jsonschema==4.17.1
jupyter-server==1.23.3
jupyter_client==7.4.7
jupyter_core==5.1.0
jupyterlab==3.5.0
jupyterlab-pygments==0.2.2
jupyterlab_server==2.16.3
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack-python==0.5.6
nbclassic==0.4.8
nbclient==0.7.1
nbconvert==7.2.5
nbformat==5.7.0
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.5
packaging==21.3
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
platformdirs==2.5.4
prometheus-client==0.15.0
prompt-toolkit==3.0.33
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.4
pure-eval==0.2.2
pycparser==2.21
pyfluent==0.2.1
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
pytz==2022.6
pywin32==305
pywinpty==2.0.9
pyzmq==24.0.1
requests==2.28.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
terminado==0.17.0
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
traitlets==5.5.0
urllib3==1.26.13
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.2
zipp==3.11.0
```

**Comment by snallamoansys** [comment]
@gibbsycfd setup.general is still not an active object. You may need to use TUI API to set gravity direction. You can check the active child objects as shown here:
![image](https://user-images.githubusercontent.com/99287292/205210756-1de9ab49-0f3b-488c-8b4c-7c2bbf4fe3ea.png)

**Comment by seanpearsonuk** [comment]
This is no longer an issue in the latest internal Fluent build (2023R2) so I'm closing it with nothing more for us to do.
