### ISSUE TITLE
solver.tui.define.models.resolved_MEA_fuelcells

### ISSUE THREAD

**Issue by xinJOBS** [pyansys/pyfluent#1175]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

`solver.tui.define.models.addon_module(3)`
`solver.tui.define.models.resolved_MEA_fuelcells`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4752\1715411722.py in <module>
----> 1 solver.tui.define.models.resolved_MEA_fuelcells
f:\miniconda\lib\site-packages\ansys\fluent\core\services\datamodel_tui.py in __getattribute__(self, name)
    257 
    258     def __getattribute__(self, name):
--> 259         attr = super().__getattribute__(name)
    260         if type(attr) == types.MethodType:
    261             path = self.path + [name]

AttributeError: 'models' object has no attribute 'resolved_MEA_fuelcells'

Cannot find the module using the tui command in the pemfc model

### 📝 Steps to reproduce

`solver.tui.define.models.addon_module(3)`
`solver.tui.define.models.resolved_MEA_fuelcells`

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
pip install ansys-fluent-core
```

**Comment by dnwillia-work** [comment]
Yeah, for the addon modules would have also expected this to be working.  I suppose we would need to make sure the dynamic configuration works as in Fluent after the first call happens.
