### ISSUE TITLE
Text command is not giving the name as output

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1209]
List = []
List=meshing.scheme_eval.scheme_eval('(tgapi-util-get-all-object-name-list)')

print(List)
[<ansys.fluent.core.services.scheme_eval.Symbol at 0x2c20f8a4bb0>]

I am getting the object name when i run the command in fluent but not in python

**Comment by pavankumarkonchada** [comment]
Hi Mkundu
The below mentioned command is giving id value but I want name of the face zone 
(tgapi-util-get-face-zone-id-list-of-object 'zone-solid)
can you please help me with this

**Comment by pavankumarkonchada** [comment]
Such that I can rename using the below syntax
(tgapi-util-rename-face-zone "old-name" "new-name")

**Comment by mkundu1** [comment]
`(tgapi-util-convert-zone-ids-to-name-strings (tgapi-util-get-face-zone-id-list-of-object 'zone-solid))` as mentioned in https://github.com/pyansys/pyfluent/issues/1212
