### ISSUE TITLE
Getting Id value but wanted the name of face zone

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1212]
The below mentioned command is giving id value but I want name of the face zone
(tgapi-util-get-face-zone-id-list-of-object 'zone-solid)
I didnot find any suitable syntax to get the face zone name

**Comment by pavankumarkonchada** [comment]
Please any one can help me with this

**Comment by mkundu1** [comment]
@pavankumarkonchada According to the [meshing TUI documentation](https://ansyshelp.ansys.com/account/secured?returnurl=/Views/Secured/corp/v222/en/flu_tcl/tgd_api_query_functions.html), `(tgapi-util-convert-zone-ids-to-name-strings (tgapi-util-get-face-zone-id-list-of-object 'zone-solid))` is what you're looking for. There doesn't seem to be a function that returns the zone-names directly.
