### ISSUE TITLE
Implementing pre-commit.ci

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyfluent#1253]
Hi @seanpearsonuk @dnwillia!

We have been recently implementing a tool called ``pre-commit.ci`` in several PyAnsys repositories. This tool is characterized for the following:

* It allows us to "get rid" of the pre-commit stage of our own workflows in favor of using a third-party tool
* This tool then runs pre-commit on its own cached resources, allowing for faster run times of pre-commit
* If the tool detects a pre-commit failure, it creates a commit to try and fix the issue encountered (this only occurs if the pre-commit hook that failed is able to reformat)
* It maintains the pre-commit hook versions updated (which by the way, dependabot does not).
* It also provides the repository with a new badge for its main README informing of the status of pre-commit on its latest run.

PyMAPDL, PyAEDT and the PyAnsys metapackage, among others, have already migrated to this tool. If you agree as well on its use, I'd be happy to implement it on your repositories:

* PyFluent
* PyFluentVisualization
* PyFluentParametric

**Comment by seanpearsonuk** [comment]
Hi @RobPasMue. Many this for this, it sounds like a nice improvement. Please proceed whenever convenient for you.
