### ISSUE TITLE
Version defaulting

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1262]
By default, the launch function should try to launch the latest installed version of Fluent (greatest value of the AWP root index).

**Comment by RebelYoung** [comment]
[https://github.com/pyansys/pyfluent/issues/1268](url)
This is my problem for the lastest `launcher.py`.
It is not good for catch my version in the work station.

**Comment by RebelYoung** [comment]
I test the command in two virtual enviroments, both version `0.11.0` and  `0.12.1`, 
`launch_fluent` works in previous one.
![d5fe4009eb9c9d1c6ae0b9b04f1034c](https://user-images.githubusercontent.com/59256512/212531187-41fec072-f649-4ff7-800b-dacd33e194d9.png)
in left `py38f11` has the `version 0.11.0` package.

**Comment by mkundu1** [comment]
We shall have the following 3 options to specify Fluent launch path from PyFluent:

1. default - via AWP_ROOT env vars
2. user override - via the product_version param in launch_fluent
3. developer override - via PYFLUENT_FLUENT_ROOT env var

Other options are redundant and will be removed.

**Comment by seanpearsonuk** [comment]
> We shall have the following 3 options to specify Fluent launch path from PyFluent:
> 
> 1. default - via AWP_ROOT env vars
> 2. user override - via the product_version param in launch_fluent
> 3. developer override - via PYFLUENT_FLUENT_ROOT env var
> 
> Other options are redundant and will be removed.

This will be a positive change. Thanks, @mkundu1.

**Comment by RebelYoung** [comment]
> We shall have the following 3 options to specify Fluent launch path from PyFluent:
> 
> 1. default - via AWP_ROOT env vars
> 2. user override - via the product_version param in launch_fluent
> 3. developer override - via PYFLUENT_FLUENT_ROOT env var
> 
> Other options are redundant and will be removed.

Does it launch the lastest fluent.exe version automatically ?
It means, 
if I had `23.1` and `22.2`, it choose `23.1` automatically. 
And, if it only installed `22.2`, it launch `22.2` automatically.

**Comment by mkundu1** [comment]
> > We shall have the following 3 options to specify Fluent launch path from PyFluent:
> > 
> > 1. default - via AWP_ROOT env vars
> > 2. user override - via the product_version param in launch_fluent
> > 3. developer override - via PYFLUENT_FLUENT_ROOT env var
> > 
> > Other options are redundant and will be removed.
> 
> Does it launch the lastest fluent.exe version automatically ? It means, if I had `23.1` and `22.2`, it choose `23.1` automatically. And, if it only installed `22.2`, it launch `22.2` automatically.

Yes, that's right
