### ISSUE TITLE
Built documentation getting compressed into a zipped file.

### ISSUE THREAD

**Issue by alikasim72** [pyansys/pyfluent#1272]
Currently, when building documentation in the gh-pages branch, the built html files/folders for the releases are compressed into a zip file. Seems like there is a bug in the workflow file which I'm currently fixing. 

cc: @jorgepiloto

**Comment by jorgepiloto** [comment]
Thanks for opening this, @alikasim72.

**Comment by alikasim72** [comment]
Solve in PR #1273
