### ISSUE TITLE
Missing TUI object

### ISSUE THREAD

**Issue by PyPablo** [pyansys/pyfluent#1287]
### 📝 Description of the feature

In TUI it is possible to activate 

/adjoint/geometry/parameterize-and-explore/design-conditions

This is missing under PyFluent TUI api

**Comment by mkundu1** [comment]
These menus are available are runtime:
![image](https://user-images.githubusercontent.com/94432368/213733846-9ccf9d5f-c685-45f3-9883-7ef23c5c43ea.png)

In Fluent, these menus are inserted at runtime, the information about them is not available in static info. So, we don't have generated classes for these menus in PyFluent.

**Comment by PyPablo** [comment]
Great. Thanks @mkundu1 .
