### ISSUE TITLE
Bug located in scheme_eval.string_eval()

### ISSUE THREAD

**Issue by prmukherj** [pyansys/pyfluent#1288]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The string eval call does not return any error for any arbitrary entries. It returns _false_ which might be a valid output for some cases. This needs fixing perhaps from the server side?
@mainakk, Added this issue as per our discussion.

### 📝 Steps to reproduce

 >>> solver = pyfluent.launch_fluent()
 >>> solver.scheme_eval.string_eval("(a)")

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
.
```

**Comment by mkundu1** [comment]
Fix merged in Fluent
