### ISSUE TITLE
Missing HTTPS prefix in json_url parameter for multi-version

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/pyfluent#1290]
🐞 **Problem**
The dropdown menu for multi-version is not working, see https://fluent.docs.pyansys.com/release/0.12/.

The reason is that the webpage is not able to find the "versions.json" file, as the `json_url` parameter in the `conf.py` file is missing the `https` prefix.

**Comment by mkundu1** [comment]
Keeping this open to fix this in release branch and other repo.

**Comment by dnwillia-work** [comment]
@mkundu1 @alikasim72 Is this issue sorted out?

**Comment by mkundu1** [comment]
Yeah, there is no pending task AFAIK, closing
