### ISSUE TITLE
Issue in passing value() in material property

### ISSUE THREAD

**Issue by mrf6166** [pyansys/pyfluent#1323]
by selecting e.g., 'ideal-gas' option in 'density', value is not required but it is still available in dir of the density:

-  session.setup.materials.fluid['air'].density.option()

>>>'ideal-gas'

- dir(session.setup.materials.fluid['air'].density)

>>>['__annotations__', '__call__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_flproxy', '_is_protocol', '_name', '_parent', '_print_state_helper', '_setattr', '_state_type', 'child_names', 'command_names', 'compressible_liquid', 'expression', 'flproxy', 'fluent_name', 'get_active_child_names', 'get_active_command_names', 'get_active_query_names', 'get_attr', 'get_attrs', 'get_state', 'is_active', 'is_read_only', 'obj_name', 'option', 'parent', 'path', 'piecewise_linear', 'piecewise_polynomial', 'polynomial', 'print_state', 'query_names', 'real_gas_nist', 'rgp_table', 'set_flproxy', 'set_state', 'to_python_keys', 'to_scheme_keys', 'user_defined_function', '**_value_**']

- session.setup.materials.fluid['air'].density.value
>>><ansys.fluent.core.solver.settings_231.value.value at 0x1dfdc24c250>

- session.setup.materials.fluid['air'].density.value()
>>>RuntimeError: api-get-var: the object is not active
Error Object: setup/materials/fluid/air/density/value

**Comment by dnwillia-work** [comment]
Looks like the behavior is correct.  The `value` object is inactive when the ideal gas model is active becuase it's no longer required.  It's important that you check the `is_active` property or use `get_active_child_names` to query what is available.
