### ISSUE TITLE
support dimensions argument in Quantity constructor

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1341]
as discussed, support dimensions argument in Quantity constructor. It would be a list of *upto* 9. It should be possible to pass in fewer so that Quantity assumes a tail of all zeros.

**Comment by cj-hodgson** [comment]
@millerj97 Has this already been tested in pyfluent by your testing of Quantity class?

**Comment by millerj97** [comment]
@cj-hodgson dimensions argument was not included, I will add a test for this and update the regression test to include the required arguments
