### ISSUE TITLE
Text command not working

### ISSUE THREAD

**Issue by pavankumarkonchada** [pyansys/pyfluent#1349]
(rpgetvar 'dpm/lowest-mass) not working in  2022 r2
Please any body can help me on this

**Comment by pavankumarkonchada** [comment]
It is working in ansys 19.2, but not in 2022r2. Please any body can help me with this

**Comment by snallamoansys** [comment]
@pavankumarkonchada This is related to fluent DPM model rpvars. Please raise a service request through customer portal so that the query is answered in an appropriate channel.

**Comment by dnwillia-work** [comment]
This issue is not related to PyFluent so I'm closing it.
