### ISSUE TITLE
Issue with session.solution.report_definitions.volume gives unexpected error

### ISSUE THREAD

**Issue by jharming** [pyansys/pyfluent#1364]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When assigning volume reports to session.solution.report_definitions.volume it gives an unexpected error

From fluent GUI i get this error in console:
Error: eval: unbound variable
Error Object: allowed-values

I dont have this issue when assigning  to session.solution.report_definitions.surface

I tried 

`session.solution.report_definitions.volume.create('max-afe-chip-temp')
session.solution.report_definitions.volume.create('max-inv-chip-temp')
session.solution.report_definitions.volume.create('max-temp-heatsink-afe')
session.solution.report_definitions.volume.create('max-temp-heatsink-inv')

session.solution.report_definitions['max-afe-chip-temp'] = settings['reportsVolume']['max-afe-chip-temp']
session.solution.report_definitions['max-inv-chip-temp'] = settings['reportsVolume']['max-inv-chip-temp']
session.solution.report_definitions['max-temp-heatsink-afe'] = settings['reportsVolume']['max-temp-heatsink-afe']
session.solution.report_definitions['max-temp-heatsink-inv'] = settings['reportsVolume']['max-temp-heatsink-inv']
`
I get an error for each of the fire last lines, but every time I run the next line the previous line in fluent GUI changes away from invalid. I also tried using method .set_state() but again same error

### 📝 Steps to reproduce

session.solution.report_definitions.volume.create('max-afe-chip-temp')
session.solution.report_definitions['max-afe-chip-temp'].set_state({'report_type': 'volume-max',
  'field': 'temperature',
  'average_over': 1,
  'per_zone': False,
  'zone_names': ['dcb-1.1', 'dcb-1.2', 'dcb-1.3'],
  'expr_list': None})

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.8
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pyfluent.git@472b0c088a0e5040ba23138e87c2cb5184db86c3#egg=ansys_fluent_core
ansys-platform-instancemanagement==1.0.3
appdirs==1.4.4
asttokens==2.2.1
backcall==0.2.0
cloudpickle==2.2.1
colorama==0.4.6
comm==0.1.2
debugpy==1.6.6
decorator==5.1.1
entrypoints==0.4
executing==1.2.0
googleapis-common-protos==1.58.0
grpcio==1.51.1
h5py==3.8.0
importlib-metadata==6.0.0
ipykernel==6.21.0
ipython==8.9.0
jedi==0.18.2
jupyter_client==7.4.9
jupyter_core==5.2.0
matplotlib-inline==0.1.6
nest-asyncio==1.5.6
numpy==1.24.1
packaging==23.0
pandas==1.5.3
parso==0.8.3
pickleshare==0.7.5
platformdirs==2.6.2
prompt-toolkit==3.0.36
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.4
pure-eval==0.2.2
Pygments==2.14.0
python-dateutil==2.8.2
pytz==2022.7.1
pywin32==305
pyzmq==25.0.0
six==1.16.0
spyder-kernels==2.4.2
stack-data==0.6.2
tornado==6.2
traitlets==5.9.0
wcwidth==0.2.6
zipp==3.12.0
```

**Comment by dnwillia-work** [comment]
Sean, Mainak any idea what is wrong here?

**Comment by snallamoansys** [comment]
Could this be related to this issue reported before? [https://github.com/pyansys/pyfluent/issues/473](url). We have faced issues in setting the dictionary directly for volume integral report definition.

**Comment by jharming** [comment]
Then I have something to look forward  to

**Comment by seanpearsonuk** [comment]
@jharming I asked a work experience student to test this with 2023R1. It seems to work just as in 2023R2:

![image](https://user-images.githubusercontent.com/93727996/222397157-3ee10fd1-c4bf-4ada-a879-a37f66f6918f.png)

Please let us know if there is some additional nuance missed here. Thanks.

**Comment by jharming** [comment]
Hi,
first I create the volume report
`session.solution.report_definitions.volume.create('max-afe-chip-temp')`
Then I assign it 
`session.solution.report_definitions['max-inv-chip-temp'] = {'report_type': 'volume-max',
                                                             'field': 'temperature',
                                                             'average_over': 1,
                                                             'per_zone': False,
                                                             'zone_names': ['inv1d1',
                                                              'inv1d2',
                                                              'inv1t1',
                                                              'inv1t2',
                                                              'inv2d3',
                                                              'inv2d4',
                                                              'inv2t3',
                                                              'inv2t4',
                                                              'inv3d5',
                                                              'inv3d6',
                                                              'inv3t5',
                                                              'inv3t6'],
                                                             'expr_list': None}`

When I do this I get an error in script and fluent
![error_fluent](https://user-images.githubusercontent.com/79579708/222463516-ea64e8c2-9dda-4cf3-b0d1-71d5cabed9f8.png)
If I double click in the fluent report then it changes from invalid to valid

**Comment by jharming** [comment]
Just to add. If I continue adding the next volume report I get a new error but the "invalid" note from the previous report dissappear.

**Comment by seanpearsonuk** [comment]
> Just to add. If I continue adding the next volume report I get a new error but the "invalid" note from the previous report dissappear.

Even weirder. I will have another look with the work experience student.

**Comment by jharming** [comment]
In principle I would just assign all my volume reports like the other reports. i.e. like this
`session.solution.report_definitions.surface = settings['reportsSurface']`
here I don't create the report first and then assign.
Anyhow first step is to avoid the error in the first place :)

**Comment by seanpearsonuk** [comment]
@jharming , iff `expr_list` is included in the input dict, there is an issue. It is a StringList but has no allowed-values attribute, which is wrong. I will check again the 2023R2 behaviour to see if it's already corrected there. If not, we'll expedite a solution.

**Comment by seanpearsonuk** [comment]
@jharming, it's still broken in 2023R2 so we'll work for a fix.
 I will try to provide you a fix.

**Comment by jharming** [comment]
So it will be fixed in 2023r2?

**Comment by seanpearsonuk** [comment]
That will be a n immediate fix even for 2023r1. It still shows the error in Fluent but the exception is handled in PyFluent now

**Comment by seanpearsonuk** [comment]
@jharming I confirm that set_state calls fail with the Fluent-side `allowed-values` error iff `expr_list` is included in the state. As a workaround, you can omit `expr_list` from the state dictionary, and set_state will behave well (checked with 2023R2 just now and with 2023R1 by our work experience student) . Since you are setting it to None, it is redundant anyway.

My branch solves issues for `allowed_values()` method calls on parameters like `expr_list` which omit the `allowed-values` attribute.

@gyeole @h-krishnan I think we need to resolve the `expr_list` `allowed-values` omission in Fluent. Ideally, the base classes can ensure the existence of salient attributes.

**Comment by seanpearsonuk** [comment]
@jharming corrected in Fluent 2023 R**2**
