### ISSUE TITLE
Bug located in solver.tui.define.boundary_conditions

### ISSUE THREAD

**Issue by MarteauPiqueur** [pyansys/pyfluent#1374]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I try to apply a specific boundary condition such as a mass flow inlet, it is not found in python and I get the following error: RuntimeError: menu not found
I ran the following line to just see if this type of boundary condition was available:
solver.tui.define.boundary_conditions.set.mass_flow_inlet() as shown in the exemples but with a velocity inlet for the elbow.

It is strange because both velocity_inlet and pressure_outlet are available and working for me but not mass_flow_inlet. 
![Error_pyfluent](https://user-images.githubusercontent.com/106227258/220055065-90dd3f09-136b-43e0-992b-d0e14e5e6684.png)

### 📝 Steps to reproduce

import ansys.fluent.core as pyfluent

pyfluent.set_fluent_path("[insert path]")
solver = pyfluent.launch_fluent(precision = "double", version="2d", mode="solver", show_gui=True)

msh_filename = "[insert mesh]"
solver.file.read(file_type="mesh", file_name=msh_filename)
solver.tui.mesh.check()

solver.tui.define.units("length", "mm")
solver.tui.define.models.viscous.laminar("yes")
solver.setup.models.energy.enabled = False

solver.tui.define.materials.copy("fluid", "ethyl-alcohol-liquid")
#solver.tui.define.materials.copy("solid", "ethyl-alcohol-liquid") #Import with 2023R1 Pro the inconel 718

solver.tui.define.boundary_conditions.fluid(
    "epaisseur_0.5mm_surface",
    "yes",
    "ethyl-alcohol-liquid",
)

solver.tui.define.boundary_conditions.set.mass_flow_inlet()

#solver.exit()

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
ansys.fluent.core
```

**Comment by jharming** [comment]
Hi, this works for me: Here is an example where the named selection is 'extfanout', and I have some equation to set values. I prefer passing a dict instead of using tui commands It is easier to read what you are doing
solver.setup.boundary_conditions.mass_flow_inlet = {'extfanout': {'frame_of_reference': 'Absolute',
  'flow_spec': 'Mass Flow Rate',
  'mass_flow': {'option': 'value', 'value': 'ExtFanMassFlowSet'},
  't0': {'option': 'value', 'value': 'ExtFanOutTemp'},
  'gauge_pressure': {'option': 'value', 'value': 0},
  'direction_spec': 'Normal to Boundary',
  'ke_spec': 'Intensity and Viscosity Ratio',
  'turb_intensity': 0.05,
  'turb_viscosity_ratio': 10}}

**Comment by jharming** [comment]
just a comment. You could also when creating the solver session, then you can set the BC up in fluent and then use this to read the dictionary.
solver.setup.boundary_conditions.mass_flow_inlet()
Out[31]: 
{'extfanout': {'frame_of_reference': 'Absolute',
  'flow_spec': 'Mass Flow Rate',
  'mass_flow': {'option': 'value', 'value': 'ExtFanMassFlowSet'},
  't0': {'option': 'value', 'value': 'ExtFanOutTemp'},
  'gauge_pressure': {'option': 'value', 'value': 0},
  'direction_spec': 'Normal to Boundary',
  'ke_spec': 'Intensity and Viscosity Ratio',
  'turb_intensity': 0.05,
  'turb_viscosity_ratio': 10}}

**Comment by MarteauPiqueur** [comment]
Thank you a lot for your answer, it is way clearer now ! For the names of the categories in the dict you found them in a file or by looking at other's solutions ? Also I have now implemented the following code because I am in laminar flow and I am not considering energy stuff yet:
![Error_pyfluent2](https://user-images.githubusercontent.com/106227258/220152187-8319748c-085d-4261-b4ee-7e08e7716518.png)
But I have that error:
![Error_pyfluent3](https://user-images.githubusercontent.com/106227258/220152435-441f18b6-d4e3-4d1b-8497-bfbead9707ca.png)
I have already checked that the boundary I am trying to work with is righfuly called 'inlet' as I have automatized the generation of .msh file earlier with these boundary names

**Comment by jharming** [comment]
Sorry I cant help you with that.

but some other ideas to debug is to try to set it first in the fluent gui and then try to read and write to it using
solver.setup.boundary_comditions.mass_flow_inlet['inlet']

Some usfeull commands to find settings I use
dir(session)
dir(session.boundary_conditions)

To find out which categories for each the recommended method is when running a session in GUI mode, then set it up in fluent and then call the method. e.g.
settings = session.boundary_conditions.mass_flow_inlet()

This you have to do one time only.

When you have found the settings then I have chosen to use .json files to store the different settings. e.g.

`
import json
namedExpressions = session.setup.named_expressions()
    with open('namedExpressions.json', 'w') as fp:
        json.dump(namedExpressions, fp, indent = 4)
`

and to read them

`
with open('namedExpressions.json', 'r') as fp:
        namedExpressions = json.load(fp)
`

**Comment by mkundu1** [comment]
@MarteauPiqueur Both the following syntax will work for querying by boundary names:
```
>>> solver.setup.boundary_conditions["inlet1"]()
{'frame_of_reference': 'Absolute', 'flow_spec': 'Mass Flow Rate', 'mass_flow': {'option': 'value', 'value': 0}, 't0': {'option': 'value', 'value': 300}, 'gauge_pressure': {'option': 'value', 'value': 0}, 'direction_spec': 'Normal to Boundary', 'ke_spec': 'Intensity and Hydraulic Diameter', 'turb_intensity': 0.099999994, 'turb_hydraulic_diam': 0.16}
>>> solver.setup.boundary_conditions.mass_flow_inlet["inlet1"]() 
{'frame_of_reference': 'Absolute', 'flow_spec': 'Mass Flow Rate', 'mass_flow': {'option': 'value', 'value': 0}, 't0': {'option': 'value', 'value': 300}, 'gauge_pressure': {'option': 'value', 'value': 0}, 'direction_spec': 'Normal to Boundary', 'ke_spec': 'Intensity and Hydraulic Diameter', 'turb_intensity': 0.099999994, 'turb_hydraulic_diam': 0.16}
```

**Comment by seanpearsonuk** [comment]
@MarteauPiqueur In te original post, were you trying to change the bc type. I played with it in the TUI (first step for figuring out TUI API usage):
```
/define/boundary-conditions> zone-type
zone id/name/list [] 5

external-type> velocity-inlet

/define/boundary-conditions> zone-type
zone id/name/list [] 6

external-type> mass-flow-inlet
```
That works, and then I can craft the API calls based on that.

For settings API, I can change type thus:

```
>>> s.setup.boundary_conditions.change_type(zone_list=["velocity-inlet-5"], new_type="mass-flow-inlet")
'input-type'
```
