### ISSUE TITLE
Document REMOTING_SERVER_ADDRESS env var usage to fix VPN related issues

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#1381]

**Comment by seanpearsonuk** [comment]
Is there any way to make this env var unneeded by updating the server code in some way?

**Comment by mkundu1** [comment]
Previous findings:

Here is the equivalent python code for determining the ip address in server:
![2023-02-21 07_59_20-Administrator_ Command Prompt - python](https://user-images.githubusercontent.com/94432368/220675423-05cd7b2c-ddc5-41aa-a2ad-84a5b640a5db.png)
We choose the first ip address from the above list. In my case, when VPN is connected, the first one is incorrect, and I need to set the second one to REMOTING_SERVER_ADDRESS to get the connection working. The list order seems to be determined by the operating system. I've experimented with some network settings as per [this post](https://www.windowscentral.com/how-change-priority-order-network-adapters-windows-10) to change the network adaptor priority but that didn't help.

**Comment by mkundu1** [comment]
We can try to determine the correct ip address before launching Fluent using a fake grpc server which we'll set to REMOTING_SERVER_ADDRESS during launching Fluent.
