### ISSUE TITLE
launch_fluent start_instance documentation

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1438]
The description could be more straightforward, starting with the True case. 
"Whether to start a local Fluent instance. The default is None, which indicates True. Otherwise, use ... < rest as current doc >

**Comment by seanpearsonuk** [comment]
The description could be more straightforward, starting with the True case.

**Comment by RebelYoung** [comment]
Why can not I connect  to a existed fluent, by
```
solver=pyfluent.launch_fluent(
    # product_version='22.2.0',
    start_instance=False,
    ip='192.168.0.1',
    port=49818)
```
![image](https://user-images.githubusercontent.com/59256512/229355535-6ff2dfdb-8aea-4f72-ac32-82db7853d3ff.png)
![image](https://user-images.githubusercontent.com/59256512/229355534-7be113e9-335c-44c0-b24a-f63cc85d756a.png)
![image](https://user-images.githubusercontent.com/59256512/229355574-02161336-3990-4053-aac4-5252833f9a97.png)
