### ISSUE TITLE
fluent_connection module only exposes MonitorThread

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1457]
- MonitorThread looks like part of _FluentConnection only so does not need to be public and documented.
- FluentConnection implicitly adds to the public interfaces of public, documented session classes. I think we should either
  - remove the getattr that provides this delegation, and make the methods provided by FluentConnection explicit in the public interfaces, or
  - document the public methods implicitly acquired from _FluentConnection as if they are explicitly implemented publicly

**Comment by seanpearsonuk** [comment]
Looking at this again, I guess that if the second point is true then the first point becomes false.

**Comment by hpohekar** [comment]
@seanpearsonuk yes because all other members are private.

**Comment by seanpearsonuk** [comment]
@hpohekar the second bullet point in the issue description is the key one. `class FluentConnection` should be public for the reasons given.
