### ISSUE TITLE
Tree of contents is in a keyhole

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1460]
Very difficult to navigate this. Can we make it more user-friendly?

**Comment by hpohekar** [comment]
@seanpearsonuk please share a link of docs related to this issue. Thank you.

**Comment by seanpearsonuk** [comment]
![image](https://user-images.githubusercontent.com/93727996/226560299-0230f352-e762-4721-a6bb-79d9fd93830d.png)

**Comment by seanpearsonuk** [comment]
https://fluent.docs.pyansys.com/dev/api/solver/datamodel/flicing/Case/App/Adaptation/State/index.html

**Comment by seanpearsonuk** [comment]
@hpohekar

**Comment by dnwillia-work** [comment]
I guess you mean that there is this long hierarchy to traverse to what you want?

**Comment by hpohekar** [comment]
I think we can use following option.

![image](https://user-images.githubusercontent.com/106588300/227173898-bdb45970-9612-459e-b20d-416fed1ce1fe.png)

**Comment by hpohekar** [comment]
otherwise PyAEDT uses this option in `conf.py`

![image](https://user-images.githubusercontent.com/106588300/227174417-2e384214-8650-409e-81fc-d7bfcf965d27.png)

**Comment by dnwillia-work** [comment]
The other thing that would help a bit would be if we could drag the frame separating the tree from the content left/right.  Not sure how one even gets something like that done.

**Comment by seanpearsonuk** [comment]
> I guess you mean that there is this long hierarchy to traverse to what you want?
> 
> One thing that would help would be if the left hand side tree did not include the parent prefixes into the children. Object names get covered up. Though, that has it's limitations too, probably you can only go so deep.

A lot of whitespace on the left, while everything squashed and hidden on the right.

**Comment by dnwillia-work** [comment]
Yeah, ok, so in the tree.  Totally agree, maybe there is a way to control the amount that each level is indented...

**Comment by hpohekar** [comment]
@seanpearsonuk @dnwillia 

We have resolved this issue. Same is applicable to TUI as well.

![image](https://user-images.githubusercontent.com/106588300/228206027-a337fdd7-c85d-42c2-badd-fb4f29d39333.png)

Thank you.

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk @dnwillia
> 
> We have resolved this issue. Same is applicable to TUI as well.
> 
> ![image](https://user-images.githubusercontent.com/106588300/228206027-a337fdd7-c85d-42c2-badd-fb4f29d39333.png)
> 
> Thank you.

is it merged?

**Comment by hpohekar** [comment]
> > @seanpearsonuk @dnwillia
> > We have resolved this issue. Same is applicable to TUI as well.
> > ![image](https://user-images.githubusercontent.com/106588300/228206027-a337fdd7-c85d-42c2-badd-fb4f29d39333.png)
> > Thank you.
> 
> is it merged?

not yet, but we have started nightly doc build on current PR. We can see the changes within next 1 hour.
