### ISSUE TITLE
Add suport for older verions or guide in how to implement it

### ISSUE THREAD

**Issue by SuperMechaDeathChrist** [pyansys/pyfluent#1471]
### 📝 Description of the feature

I am currently using the 2019R3 (19.5.0) version of ansys, and I am trying to adapt or modify pyansys to support it without having to upgrade my ansys version. It is inconvinent to upgrade my ansys installation at the moment because of compatibility issues between my current study cases.
I know the developers might not have interest in supporting older versions, but maybe you could give me some pointers in how to implement it myself.

So far, I made a few modifications that permit me to launch my version of fluent.

The check health service gets stuck never returning a successful connection status, but ignoring this seems to permit me to connect.

It exits on error, so I know it's connected and can send basic commands, such as exit-server (I observed this while running with gui).

Trying this:
```solver.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")```
triggers this error: 
```RuntimeError: Datamodel rules not found```

### 💡 Steps for implementing the feature

Maybe a quick guide or simple pointers in what parts of the code i need to modify or add regarding a specific ansys version.
I only need partial support at the moment (meshing, setting up boundary conditions, solving).

**Comment by seanpearsonuk** [comment]
@SuperMechaDeathChrist there is no easy way to support version older than 2022R2 - that's the first version with all the necessary APIs. PyFluent Meshing workflow will probably work with older Fluent versions, but that's untested.
