### ISSUE TITLE
Reading the project file failed with following error: More than one case file is present in: D:\Working_Dir

### ISSUE THREAD

**Issue by tejalprabhu01** [pyansys/pyfluent#1478]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

when there are more than one case files in the directory where flprj exists, user gets following error while reading a parametric project using casereader

ERROR: Reading the project file failed with following error: More than one case file is present in: D:\Working_Dir Traceback (most recent call last):
  File "D:\ANSYSInstallation\ANSYS Inc\v232\optiSLang\lib\python3.7\lib\site-packages\ansys\fluent\core\filereader\casereader.py", line 89, in __init__
    case_filepath = _get_case_filepath(dirname(project_filepath))
  File "D:\ANSYSInstallation\ANSYS Inc\v232\optiSLang\lib\python3.7\lib\site-packages\ansys\fluent\core\filereader\casereader.py", line 209, in _get_case_filepath
    raise RuntimeError(f"More than one case file is present in: {project_dir_path}")
RuntimeError: More than one case file is present in: D:\Working_Dir

@mkundu1 @seanpearsonuk 

### 📝 Steps to reproduce

from ansys.fluent.core.filereader.casereader import CaseReader
reader = CaseReader(project_filepath=project_filepath)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R2

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
pyfluent
pyfluent-parametric
```

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 As you might know, in the present design, each `Case` object is associated with a single underlying case file, so I think we should introduce a `Project` class which would provide access to the underlying `Case` objects.

**Comment by tejalprabhu01** [comment]
> @tejalprabhu01 @prmukherj proposal:
> 
> ```
> class Project:
>    def __init__(self, project_filepath: str) -> None
>    def cases(self) -> list (or dict)
>    def case(self, id: Union[int, str]) -> Case
> ```
> 
> ```
> >>> prj = Project(prj_path)
> >>> prj.cases()
> [[0, "elbow.cas.h5"], [1, "mixer.cas.h5"]]
> >>> cas = prj.cas(0)
> >>> cas.num_dimensions()
> 3
> ```

@seanpearsonuk may be I am not a 100% clear on the concept, but can a Fluent project be associated with multiple cases?

**Comment by seanpearsonuk** [comment]
So, the case file location should be obtained from the xml file. Are you relying on the ability to do this based on project file path input?

**Comment by seanpearsonuk** [comment]
@prmukherj we need to get the case file path by reading the xml file (flprj)
