### ISSUE TITLE
Case class is undocumented

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1484]
Case class and other code here contains docstrings: https://github.com/pyansys/pyfluent/blob/main/src/ansys/fluent/core/filereader/case.py

...but they don't appear in the docs:
https://fluent.docs.pyansys.com/dev/api/general/case_reader.html

which is apparently all based on rst file.

Note that this code itself is subject to change: #1464.

**Comment by mkundu1** [comment]
@seanpearsonuk @hpohekar case_reader.rst doesn't have module documentation. Same with data_transfer.rst.

**Comment by hpohekar** [comment]
@seanpearsonuk Do we want to document it to current `case_reader.rst` ?

**Comment by seanpearsonuk** [comment]
We want to be able to see the docstrings that are in case.py without duplicating anything in rst files. @hpohekar @mkundu1
