### ISSUE TITLE
Method is_read_only() returns None 

### ISSUE THREAD

**Issue by millerj97** [pyansys/pyfluent#1489]
### Description
Using the method is_read_only() in pyfluent returns None.

### Steps to Reproduce
- launch pyfluent in solver mode
- load a case
- run a read_only command such as; print(solver.setup.boundary_conditions.is_read_only())

### Which OS?
Windows

### Which Ansys Version?
232

### Which Python?
3.7

### Installed Packages
ansys-api-fluent                      0.3.10
ansys-api-platform-instancemanagement 1.0.0b3
ansys-fluent-core                     0.13.dev3 
ansys-platform-instancemanagement     1.0.3
appdirs                               1.4.4
googleapis-common-protos              1.58.0
grpcio                                1.51.3
h5py                                  3.8.0
importlib-metadata                    6.1.0
numpy                                 1.21.6
pandas                                1.3.5
pip                                   23.0.1
protobuf                              3.20.3
protoc-gen-swagger                    0.1.0
python-dateutil                       2.8.2
pytz                                  2022.7.1
setuptools                            47.1.0
six                                   1.16.0
typing_extensions                     4.5.0
zipp                                  3.15.0

**Comment by seanpearsonuk** [comment]
@cj-hodgson @millerj97 PR will be merged today
