### ISSUE TITLE
meshing queries updates

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1579]
- change from camel case to snake case 
    - I note that this is done in PR, thanks 
- reduce number of functions by grouping them and adding more arguments (gRPC)
    - E.g., all get_face_zones_* and get_face_zone_idlist_* can be merged and arguemts added (use the oneOf feature)   
- make interface easier to use e.g., in `GetZonesOfType("velocity-inlet")` and related functions the required argument values are obscure. We can add enums in the proto file.
- add the new RPCs to the existing proto file and implement them in PyFluent, but do not document them and indicate that they are unsupported by 24R1.

**Comment by hpohekar** [comment]
@seanpearsonuk 

We are refactoring and  reducing number of gRPC helper functions. (ADO PR related to T830826 )

We have improved error handling to get idea about allowed required argument values in 

https://github.com/pyansys/pyfluent/pull/1585
