### ISSUE TITLE
Summary text for gRPC services is too technical

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#1586]
We should tell what each service offers instead. "Wrapper over gRPC" is not helpful.

![image](https://github.com/pyansys/pyfluent/assets/93727996/2f288bb9-17bf-42b6-af1c-2968210ebebf)

**Comment by hpohekar** [comment]
@seanpearsonuk Are you going to add description for above summary ? or shall I update it ?

**Comment by seanpearsonuk** [comment]
@hpohekar, If you want to create a PR, that's fine too. We can make suggestions within the PR too.

**Comment by hpohekar** [comment]
@seanpearsonuk Added description in https://github.com/pyansys/pyfluent/pull/1585.
