### ISSUE TITLE
Problem with running PyFluent on server

### ISSUE THREAD

**Issue by hvrooij** [pyansys/pyfluent#1592]
Running PyFluent simulations on my own laptop works perfectly fine, however when running the same simulations on a server (Snellius in this case) with the same version of Python, Fluent and PyFluent installed, after a few minutes the processors go on sleeping mode and do not seem to enter the running mode again. Therefore only a few timesteps can be performed. 

Attached to this issue are .txt versions of the python file I use (MWE_PyFluent_Snellius.txt) and of the batch file (Simulation_script_MWE.txt). 

I could not find anyone else with a similar problem, so if anyone has any idea what causes this problem, please let me know!

[MWE_PyFluent_Snellius.txt](https://github.com/pyansys/pyfluent/files/11462794/MWE_PyFluent_Snellius.txt)
[Simulation_script_MWE.txt](https://github.com/pyansys/pyfluent/files/11462795/Simulation_script_MWE.txt)

**Comment by seanpearsonuk** [comment]
@hvrooij sorry but this does not seem to indicate any issue with the PyFluent software.
