### ISSUE TITLE
PyFluent: GRPC_ERROR while enabling the Meshing Workflows

### ISSUE THREAD

**Issue by ypatel-qa** [pyansys/pyfluent#203]
I am testing on Linux machine lebfluintrh08 using Fluent build id 153. I am using virtual environment `python -m venv .venv`

To reproduce:
(1) Run following lines on Linux via Python:
```
import ansys.fluent.core as pyfluent
s = pyfluent.launch_fluent(meshing_mode=True, precision="double", processor_count="4")
s.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")

[ypatel@lebfluintrh08][/net/nfs.lebisilon/home/ypatel/pyfluent/pyfluent/examples/00-fluent/mixing_elbow]> /net/nfs.lebisilon/home/ypatel/pyfluent/pyfluent/.venv/bin/python
Python 3.8.8 (default, Aug 11 2021, 06:52:42)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansys.fluent.core as pyfluent
>>> import os
>>> s = pyfluent.launch_fluent(meshing_mode=True, precision="double", processor_count="4")
>>> s.workflow.InitializeWorkflow(WorkflowType="Watertight Geometry")
<Future at 0x7f03a21e6ca0 state=running>
>>> 2022-03-21 13:43:23,814 root         ERROR    GRPC_ERROR: The last request could not be completed because there is error in server.
```

**Comment by abhishekchitwar** [comment]
Hello Team, I am facing the same issue, which will get resolved by setting following environment variable.
 
 REMOTING_SERVER_ADDRESS=localhost 

I never face this issue in office network, however often get this error while WFH with ANSYS VPN.

Please let me know if any there are any questions.

Thanks
Abhishek

**Comment by mkundu1** [comment]
Note that, we have a doc note for `REMOTING_SERVER_ADDRESS` env. var. for Fluent's Remote Visualization Client: https://ansysproducthelpqa.win.ansys.com/account/secured?returnurl=/Views/Secured/corp/v231/en/flu_ug/flu_ug_remote_client_environment_variables.html

We can change `getIPAddr` as Sean mentioned.
