### ISSUE TITLE
Sutherland viscosity model options through settings API

### ISSUE THREAD

**Issue by snallamoansys** [pyansys/pyfluent#248]
Hi,

I can set the fluid viscosity model option to 'sutherland' through settings api but can't set the variables needed for this model. Please let me know if this model option is WIP for 2022R2. If not, user may get confused if this option is selectable but not its properties.

Regards,
Sravan

**Comment by gyeole** [comment]
@snallamoansys @dnwillia-work  This is now available in 23.1
