### ISSUE TITLE
Orthotropic conductivity setting does not work through root settings API

### ISSUE THREAD

**Issue by mkvani** [pyansys/pyfluent#390]
**Feature**: Root settings API (solid material property)
**Issue**: Solid material property for cylindrical orthotropic conductivity is not getting updated. Fluent throws error (improper list). The same API command works if executed second time in same session (after executing first time, it only sets "cyl-orthotropic" without setting any conductivity data and throws error in Fluent console. For second time execution, it updates the conductivity data correctly)

**API command used**:

``` Python


        root.setup.materials.solid['copper']={'density': {'option': 'constant', 'constant': density}, \
            'specific_heat': {'option': 'constant', 'constant': cp}, 'thermal_conductivity': {'option': 'cyl-orthotropic', \
            'var_class': {'constant': 401.0, 'cyl-orthotropic': {'k1': {'constant': tangential_cond}, \
            'direction-0': [0.0, 0.0, 0.0], 'direction-1': [0.0, 0.0, 1.0], 'k0': {'constant': radial_cond}, 'k2': {'constant': axial_cond}}}}}
```

Error message in Fluent console:

```
Error: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f

```

**Comment by seanpearsonuk** [comment]
[FLUENT BUG 684764]
