### ISSUE TITLE
session.tui.solver.define.parameters.input_parameters.edit() doesnot work with String type of parameter names

### ISSUE THREAD

**Issue by tejalprabhu01** [pyansys/pyfluent#398]
The following issue is seen in optiSLang with the attached case file

The parameter value cannot be set like this >>session.tui.solver.define.parameters.input_parameters.edit('Tin', 'Tin', 495.0)
but instead needs to be set >>session.tui.solver.define.parameters.input_parameters.edit('“Tin”', '”Tin”', 495.0)

This cannot be handled on optiSLang side as optiSLang simply queries the parameter name and uses this to set the value to this parameter.

Please find project at https://ansys-my.sharepoint.com/:u:/p/tejal_prabhu/EXkRNJzhL9dJlCbfzvf5_VwBbYuiZaBwICnAU-KLOp9faA?e=cRqOHP

**Comment by mkundu1** [comment]
@seanpearsonuk No, there are better alternatives for setting input parameters now.
