### ISSUE TITLE
missing 'field' variable leads to error while updating the volume integral report definition through settings api

### ISSUE THREAD

**Issue by snallamoansys** [pyansys/pyfluent#473]
Hi,

When we create a default volume integral report definition, the default report_type is volume-mass. For this definition, a field variable is not needed and hence is missing from the dictionary. This missing field variable leads to error if we are updating the report definition through dictionary as shown below:

![image](https://user-images.githubusercontent.com/99287292/172601536-d043eaa9-6677-4d67-8655-8f8d91292338.png)

This forces the user to follow sequence of changing report_type variable first from volume-mass to volume-average for example before updating the dictionary or changing the field. A one time update of report definition is not possible in this scenario.

Is there a way to make this work either by adding field variable to all types of report definitions or make volume-average or volume-integral as the default? Usually in GUI, when we have mass/volume type report definition, field variable is populated but greyed out as it is not needed.

**Comment by seanpearsonuk** [comment]
tested, OK
