### ISSUE TITLE
Cleanup / auto-exit of fluent processes on disconnection

### ISSUE THREAD

**Issue by lagacep-ans** [pyansys/pyfluent#481]
**del behavior**    (FIXED IN feat/finalizer https://github.com/pyansys/pyfluent/pull/480 )

When a session object is going out of scope, the connection stays alive until... the python main thread ends (the session.MonitorThread is responsible for the cleanup).

For example

```
session = pyfluent.lauch_fluent()
...
session = pyfluent.lauch_fluent()
```

Upon exiting the main thread, all is cleaned up, yes, but in the meantime the first session is left dangling.  _Having the `__del__` operation performing the exit() could be an interesting option, but limited on how the garbage collection is handled.

However, del would not work right now, as the MonitorThread keeps a reference to the session object.
 ... we can make it work with a   weakref.WeakMethod  reference instead.
 
**Jupyter notebook & process kill**

In jupyter notebook, depending of the workflows (restarting a kernel for example) the cleanup function will never be called, Also for example if the python process is killed explicitly.

**solution = timeouts?**

To fix these two issues simultaneously, it was discussed to add a "timeout" to the launcher options.
After a "disconnection", a number of minutes is counted (server side)
 timeout = N     could be 0 for an immediate exit
 timeout = -1    auto exit is disabled

(  This might require adding some code server-side, such as a modification of the remoting-on-disconnection behavior, but this framework seem to behave differently than in flremote context.  There is no printout "Information: A new client connected with server.".  @mkundu1 how is this different on PyFluent usage scenario?  )

**Comment by seanpearsonuk** [comment]
Closing: resolved by changes from @mkundu1 

cc:: @lagacep-ans
