### ISSUE TITLE
Add a get_static_info rpc for TUI API

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#483]
Currently the tuigen is failing randomly during CI run with the following error:
```
2022-06-08 11:16:24,640 root         ERROR    GRPC_ERROR: basic_string::erase: __pos (which is 18446744073709551615) > this->size() (which is 0)
```

One possible issue is the huge number of API calls to get child-menu names and help-strings at each level. We can replace those with a single get_static_info rpc call similar to the datamodel and settings API.

**Comment by seanpearsonuk** [comment]
ADO 682015
