### ISSUE TITLE
Settings API help truncates

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#533]
Viewing in jupyter land

```
help(solver.setup.models.viscous)

```
Example line in output:
```
child_names = ['model', 'options', 'spalart_allmaras_production', 'k_e...
```

**Comment by seanpearsonuk** [comment]
@dnwillia-work marked this as a **Settings API Enhancement** - do you mean that this is a Fluent-side issue, and if so are you certain?

**Comment by dnwillia-work** [comment]
I thought we had a separate label for that.  i.e. "Fluent".

**Comment by seanpearsonuk** [comment]
@hpohekar maybe jupyter can be configured to avoid this issue?

**Comment by seanpearsonuk** [comment]
ADO 704297

**Comment by mkundu1** [comment]
Fixed in PyConsole, need to do the same in PyFluent.
