### ISSUE TITLE
PrintState doesn't show surfaces list

### ISSUE THREAD

**Issue by rploconnor** [pyansys/pyfluent#535]
If I do the following:
```
session.solver.root.results.graphics.vector["velocity_vector_symmetry"] = {}
session.solver.root.results.graphics.vector["velocity_vector_symmetry"].print_state()
```
Then the state does not include "surfaces_list" in the dictionary. However, if I display the vector graphic, then it is included when I print state, as shown below.

```
name : velocity_vector_symmetry
field : velocity-magnitude
vector_field : velocity
**surfaces_list : 
  0 : elbow-fluid**
scale : 
  auto_scale : True
  scale_f : 1
style : 3d arrow
......
```
I think surfaces_list should be included in the first print_state so that the user will know all the required inputs.

**Comment by seanpearsonuk** [comment]
@rploconnor I currently see the surfaces_list even without displaying. Please reopen if you see differently now. I am using 23R1.
