### ISSUE TITLE
General CI-related maintenance tasks

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#603]
1. Run unittests and build doc for both 22.2 and 23.1 backends. This is currently commented out in ci.yml.
2. Replace PYPI_TOKEN with the token generated for the repo.
3. Replace .ci\pull_fluent_image.py with a simple bash script. It will pull the Fluent image based on `FLUENT_IMAGE_TAG` env var and remove all dangling images (`docker image prune`). Earlier we had limited disk space in the self-hosted runner, so we were cleaning up before pulling the newer image.
~4. As we are going to add more integration tests within the unittests, it is better to split the "Build and Unit Testing" job. We can run unittests in the self-hosted runner and build the package in github runner. We choose to build in github runner to build in a clean machine.~ (not important as we shall run only selected tests under the markers)
5. We don't need to run codegen for 22.2 if we can cache the output permanently.

Some of the above tasks are required to be done also in other pyfluent repos. For 1 and 4, we also need to update the list of status checks in repo's branch protection rules.

**Comment by seanpearsonuk** [comment]
Hello @hpohekar for this task, please reach out to @mkundu1 for support.

**Comment by seanpearsonuk** [comment]
@hpohekar @mkundu1 it will be good to clean up one or two outstanding tasks from this list
