### ISSUE TITLE
Lazy invocation of Fluent commands

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#612]
Lazy invocation of Fluent commands
Allow the cost of many remote calls to be avoided 
even with a coding style heavy in object interactions. 
Apply multiple settings to many objects in a loop, such 
as boundary conditions or assembly nodes - resulting in a single remote call

Mainak:
We can probably do it at grpc service level - have composite rpcs that combine   
simple rpcs, e.g. multiple writes in one go.

rpc Transaction (stream WriteRequest) returns (TransactionResponse) {}

WriteRequest is one of SetVarRequest, ExecuteCommandRequest

**Comment by mkundu1** [comment]
BatchOps service is now available (exiting issue for Linux)
