### ISSUE TITLE
Explicit attribute accessor methods on settings objects

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#618]
Right now with settings objects, we can do stuff like

default_val = setting.get_attr("default")
allowed = str_setting.get_attr("allowed-values")

We also want:

default_val = setting.default_value( )
allowed = str_setting.allowed_values( )

Only the supported methods get created. So, default_value only
exists on properties; allowed_values only exists on strings and string lists,
and so on.

**Comment by seanpearsonuk** [comment]
Specific requirements
- all nodes (i.e. available in class Base just as is_active is now:
- - read_only (fluent name "read-only?")
- all properties and arguments (i.e. all classes such as Integer, ..., RealVector, ..., so inheritance might be the best solution, possibly via mixin)
- - default_value (fluent name "default")
- all strings and string lists (again using inheritance)
- - allowed_values ("allowed-values")
- all numerical values (again using inheritance)
- - min ("min")
- - max ("max")

**Comment by prmukherj** [comment]
Sean:


![Image](https://user-images.githubusercontent.com/109645853/183632123-00fc91ef-ec84-4d68-a61a-65202abc5424.png)

**Comment by seanpearsonuk** [comment]
https://github.com/pyansys/pyfluent/pull/701
