### ISSUE TITLE
Mistake/error found in Watertight geometry meshing workflow example

### ISSUE THREAD

**Issue by jgd10** [pyansys/pyfluent#661]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues

### 🐞 Description of the bug

![image](https://user-images.githubusercontent.com/12530336/180773469-b7f31448-a32b-46dd-bd33-b5c7d389c4d8.png)

In this section of the example there looks like there's a malformed subsection in the comments for "Import Geometry".

### 📝 Steps to reproduce

See https://fluentdocs.pyansys.com/examples/00-fluent/mixing_elbow.html#import-cad-and-set-length-units

**Comment by seanpearsonuk** [comment]
The output is as it comes in the Fluent meshing console.
