### ISSUE TITLE
case reader clean up tasks

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#670]
In fact this involves changes in core and parametric packages

- update the case file path argument in parametric's CaseReader usage (remove h5 prefix)
- remove import of parametric's CaseReader in except block
- remove parametric's CaseReader
- bump the core and parametric versions

**Comment by prmukherj** [comment]
Can lispy.py also be removed from parametric? It does not have any other usages, locally - not sure if has linked usage, that's why checking. If that's the case then the entire filereader.py can be removed along with the 2 related tests.

**Comment by seanpearsonuk** [comment]
@prmukherj yes lispy.py can also be removed from parametric
