### ISSUE TITLE
Creating objects via the solver.objects.display class is failing

### ISSUE THREAD

**Issue by sujal-tipnis** [pyansys/pyfluent#68]
To reproduce:
- Start PyFluent and run the attached script.
- Please use the geometry from this [location](https://tfs.ansys.com:8443/tfs/FluentTesting/FluentTesting/_git/tutorials?path=%2Fexhaust_manifold_tui_fltg%2Fstd)
 [exhaust_manifold_s2_bug.py.txt](https://github.com/pyansys/pyfluent/files/8091674/exhaust_manifold_s2_bug.py.txt)
- Make sure to turn on the Fluent window view.
- Check the created display object. An error as shown below is observed:
![Capture](https://user-images.githubusercontent.com/97630067/154556837-0c0a10c8-6f96-4e00-ae63-29e00b660746.PNG)
- Try displaying the contour object. A crash is observed on Fluent
- This can be seen with the latest Fluent and pyFluent.

**Comment by seanpearsonuk** [comment]
fixed in 231
