### ISSUE TITLE
Report definition for expressions

### ISSUE THREAD

**Issue by ehsansadeghi1** [pyansys/pyfluent#693]
How to create a report definition for an expression? I am trying the following:

```
session.solver.tui.solve.report_definitions.add(
"dp2",
"single-val-expression",
"AreaAve([StaticPressure, inlet])-AreaAve([StaticPressure, outlet])",
"quit"
)
```

**Comment by snallamoansys** [comment]
@ehsansadeghi1, please use this command to define the report definition with an expression:

tui.solve.report_definitions.add('dp2','single-val-expression','define',"\"AreaAve(StaticPressure, ['inlet'])-AreaAve(StaticPressure, ['outlet'])\"",'q')

**Comment by mkundu1** [comment]
We should add a note or example for this in our documentation.
