### ISSUE TITLE
Add ability to specify Fluent version when launching Fluent

### ISSUE THREAD

**Issue by rploconnor** [pyansys/pyfluent#711]
### 📝 Description of the feature

Many users will have multiple versions on their machine (especially on cluster). It would be desirable to be able to specify the Fluent version when launching Fluent. Right now this is set with an environment variable. I envision that what is specified here would override what is specified in the environment variable. If nothing is specified here, then it will resort to using the environment variable.

**Comment by seanpearsonuk** [comment]
@rploconnor, either of these will now work:

pyfluent.set_ansys_version("23.1")
pyfluent.set_ansys_version(22.2)
