### ISSUE TITLE
Unexpected Boolean type for attributes

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#752]
It seems that attribute methods in flobject are returning False for unset attributes - should return None.

e.g. after reading mixing-elbow case (doesn't matter what case):

```
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].turb_intensity.default_value()
0.05
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].turb_intensity.max()
1
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].vmag.value.min()
False
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].vmag.value.max()
False
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].vmag.value.default_value()
False
>>> s.setup.boundary_conditions.velocity_inlet['cold-inlet'].vmag.value.get_attr('default')
False
```

**Comment by seanpearsonuk** [comment]
Fluent Bug 695719

**Comment by seanpearsonuk** [comment]
@gyeole

**Comment by seanpearsonuk** [comment]
As discussed in the ADO Bug, it's difficult to express a None value unambiguously on the Scheme side.

**Comment by seanpearsonuk** [comment]
@prmukherj I belive that you can simply take the recent change in flobject.py implemented by @gyeole

**Comment by gyeole** [comment]
In Fluent to specify no limit, #f is used for min and max attribute. Hence it return false for quantities for which it is not defined

**Comment by seanpearsonuk** [comment]
In PyFluent and PyConsole, we will return None for this. I thought that this was resolved by the recent flobject.py changes.

**Comment by gyeole** [comment]
@seanpearsonuk  'None' is returned when attribute is not defined but for min and max #f is treated as valid attribute value

**Comment by seanpearsonuk** [comment]
@gyeole and which other attributes?  Just these?

**Comment by seanpearsonuk** [comment]
@prmukherj we need to put something in flobject.py in the min and max methods to convert False to None. Also standby for replies to the above questions.

**Comment by prmukherj** [comment]
@seanpearsonuk, ohk, sure.

**Comment by gyeole** [comment]
@seanpearsonuk  Only min and max are exceptions.

**Comment by seanpearsonuk** [comment]
Thanks @gyeole.  Might we change this in future? It seems like all clients of the API have to do something special for min and max (which aren't special).

**Comment by gyeole** [comment]
@seanpearsonuk  I agree. I will handle it at API level. I will create PR in a day or two.

**Comment by seanpearsonuk** [comment]
@gyeole thanks very much, that will be good.
@prmukherj nothing to change in flobject.py or any client code.  Thanks for raising this.

**Comment by prmukherj** [comment]
@seanpearsonuk, I had created a PR already, sorry for that. I'll clean up the PR and have that only for the defensive check for the command args fix as mentioned in https://github.com/pyansys/pyfluent/issues/895
