### ISSUE TITLE
Length unit changes are not respected

### ISSUE THREAD

**Issue by sujal-tipnis** [pyansys/pyfluent#76]
To reproduce:

- Start PyFluent and run the attached script.
- Please use the geometry from this [location](https://tfs.ansys.com:8443/tfs/FluentTesting/FluentTesting/_git/tutorials?path=%2Fexhaust_manifold_tui_fltg%2Fstd)
- Run the following script: 
[diam_bug.py.txt](https://github.com/pyansys/pyfluent/files/8119639/diam_bug.py.txt)
-  The length units are changed to "mm" in the solver before accessing the boundary conditions.
-  But when specifying the hydraulic diameter, the units get specified in "m".

**Comment by seanpearsonuk** [comment]
Behaviour is as expected
