### ISSUE TITLE
Session mode when connecting to running Fluent

### ISSUE THREAD

**Issue by mkundu1** [pyansys/pyfluent#787]
When we connect to already running Fluent using ip/port/password info, the resulting session should expose the correct mode based on whether Fluent is running in solver or meshing mode. At present we have the following various ways to connect to running Fluent session:

```
pyfluent.launch_fluent(start_instance=False, ip=<ip>, port=<port>)
Session.create_from_server_info_file(server_info_filepath=<filepath>)
Session(ip=<ip>, port=<port>, passsword=<password>)
Session(channel=<grpc.Channel>)
```

**Comment by RebelYoung** [comment]
What's wrong?
![image](https://user-images.githubusercontent.com/59256512/229355701-6314e5f3-dbbc-4fdb-bd4b-7d0a808af65b.png)
![image](https://user-images.githubusercontent.com/59256512/229355732-d104337a-4d26-403c-b785-e7634a7129ce.png)
![image](https://user-images.githubusercontent.com/59256512/229355756-e537d39d-62c6-43c5-b839-518681d8e7dd.png)
