### ISSUE TITLE
setup_for_fluent

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#803]
- User creates a Python journal, fluent.py, in Fluent
- First line in journal reads e.g. `setup_for_fluent(version="23.1.0", mode="meshing")`
- Subsequent lines use global PyConsole objects, `meshing`, `workflow`, `solver`, ...
- User runs: `python -i -m ansys.fluent.core fluent.py`

To get this to work seamlessly in PyFluent, the key task is to implement `setup_for_fluent` in PyFluent. `setup_for_fluent` needs to call `launch_fluent`. With `mode`="solver", it will call `launch_fluent` with mode="solver" and place the returned object in the global namespace. With `mode`="meshing", it will call `launch_fluent` with mode="meshing". From the returned `session` object, it will place `session.meshing` and `session.workflow` in the global namespace. It also needs to create a `solver` session object using the same connection information and also place it in the global namespace.

**Comment by mkundu1** [comment]
I have a test implementation of setup_for_fluent at feat/setup_for_fluent_test which can be used as a reference.

**Comment by hpohekar** [comment]
> I have a test implementation of setup_for_fluent in feat/setup_for_fluent_test branch which can be used as a reference.

Ok. Thank you, Mainak.

**Comment by seanpearsonuk** [comment]
@hpohekar this one is relatively high priority.
