### ISSUE TITLE
PyFluent: Thumbnail images are missing for some examples. 

### ISSUE THREAD

**Issue by ypatel-qa** [pyansys/pyfluent#808]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

https://fluent.docs.pyansys.com/examples/index.html

![image](https://user-images.githubusercontent.com/97630098/187762313-536969f5-134a-4b54-82ab-2f78b181237e.png)

### 📝 Steps to reproduce

https://fluent.docs.pyansys.com/examples/index.html

![image](https://user-images.githubusercontent.com/97630098/187762386-d2dad0f1-f12d-450b-8b11-7f5710fc2dd8.png)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by seanpearsonuk** [comment]
@prmukherj please can you check the current status of this.  Thanks.
