### ISSUE TITLE
Unable to read case in 23.1

### ISSUE THREAD

**Issue by egravenh** [pyansys/pyfluent#810]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When reading a case using the code,

solver_session.tui.file.read_case(case_file_name=import_filename)

the following error is displayed and the case fails to load:

Error: eval: unbound variable
Error Object: file

### 📝 Steps to reproduce

To reproduce:
1) Packages

pip install --pre ansys-fluent-core

2) Environment variables

               PYFLUENT_FLUENT_ROOT = %AWP_ROOT231%\fluent
               PYFLUENT_SHOW_SERVER_GUI = 1

3) Open a python interpreter and unzip the attached files to the working directory. 
[Static_Mixer_main.zip](https://github.com/pyansys/pyfluent/files/9466513/Static_Mixer_main.zip)
Enter the following:

import ansys.fluent.core as pyfluent

solver_session = pyfluent.launch_fluent(
    precision="double", processor_count=2, mode="solver"
)

solver_session.tui.file.read_case(case_file_name="Static_Mixer_main.cas.h5")

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pip install --pre ansys-fluent-core
```

**Comment by mkundu1** [comment]
We don't support keyword arguments in TUI. The following will work:
```
solver_session.tui.file.read_case("Static_Mixer_main.cas.h5")
```
