### ISSUE TITLE
add missing journalable data model methods

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#811]
Some data model methods: delete_child, delete_child_objects, delete_all_child_objects, fix_state and rename are missing in PyFluent. We don't even expose most of these in the proto file so there is quite a bit of work to do. We could in the meantime add dummy methods which probably should throw an explicit exception stating that the method is not yet implemented - rather than allowing a generic AttributeError to be thrown.

**Comment by seanpearsonuk** [comment]
Reassigning to @prmukherj as he has a task in the same module.

**Comment by prmukherj** [comment]
At which level this has to be available? PyMenu? or PyBasicStateContainer?
