### ISSUE TITLE
Unable to read a case file with Fluent 23R1

### ISSUE THREAD

**Issue by tejalprabhu01** [pyansys/pyfluent#819]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

session.solver.tui.file.read_case(case_file_name=input_file) gives an error when using Fluent 23R1.
Reproduced with Build Id: 135  Revision: 0fcdef55be

### 📝 Steps to reproduce

pyfluent.set_ansys_version("23R1")
pyfluent.launch_fluent()
session.solver.tui.file.read_case(case_file_name=input_file)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
pyfluent version tag 0826
```

**Comment by tejalprabhu01** [comment]
@seanpearsonuk @mkundu1

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 you don't need a patch for this bug.  It was just a usage change: keyword -> positional.
