### ISSUE TITLE
Prioritize documentation for full release versions

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#827]
"Hi PyFluent, I see that the examples on GitHub apply to the latest release of PyFluent (installed using --pre option). For example, launch_fluent 'mode' option is not available with the version that's available with the standard pip install. Since most customers will not use the --pre option, they will get tripped up when working through the example."

Applies to all repos

**Comment by prmukherj** [comment]
@seanpearsonuk @mkundu1 - So, basically should we have 2 sets of documentation (new and old)? Or shall we revert to the earlier way as of now?

**Comment by prmukherj** [comment]
@seanpearsonuk @mkundu1 , It seems this has already been done. I have confirmed for all the 3 repos - "pyfluent", "pyfluent-parametric" and "pyfluent-visualization"
