### ISSUE TITLE
Bug located in model's constant variable

### ISSUE THREAD

**Issue by mrf6166** [pyansys/pyfluent#830]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I wanted to set up Production limiter in viscous section to "true". when the value changes to "true", in TUI, the code is asking for the value of "Production limiter clip factor", and won't run any other comments until the value is filled.

also, I cannot access to the value through Python and change them

### 📝 Steps to reproduce

import ansys.fluent.core as pyfluent
session=pyfluent.launch_fluent(processor_count=2, show_gui=gui)
file1="ablation.msh.h5"
session.file.read(file_type="case", file_name=file1)
session.setup.models.viscous.model.get_attr('allowed-values')
session.setup.models.viscous.model="k-epsilon-standard"
session.setup.models.viscous.near_wall_treatment="standard-wall-fn"

session.setup.models.viscous.options.curvature_correction=False
session.setup.models.viscous.options.production_limiter=True

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
C:\Users\rfarokhi>python -m pip freeze
ansys-api-fluent==0.3.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.11.dev1
ansys-platform-instancemanagement==1.0.2
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.5
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.0.0
fastjsonschema==2.16.1
googleapis-common-protos==1.56.4
grpcio==1.47.0
h5py==3.7.0
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
ipykernel==6.15.2
ipython==8.4.0
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.1.2
json5==0.9.10
jsonschema==4.15.0
jupyter-client==7.3.5
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyterlab==3.4.5
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.1
lxml==4.9.1
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.4.3
nbclient==0.6.7
nbconvert==7.0.0
nbformat==5.4.0
nest-asyncio==1.5.5
notebook==6.4.12
notebook-shim==0.1.0
numpy==1.23.2
packaging==21.3
pandas==1.4.3
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
pkgutil-resolve-name==1.3.10
prometheus-client==0.14.1
prompt-toolkit==3.0.31
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.1
pure-eval==0.2.2
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.2.1
pywin32==304
pywinpty==2.0.7
pyzmq==23.2.1
requests==2.28.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.5.0
terminado==0.15.0
tinycss2==1.1.1
tornado==6.2
traitlets==5.3.0
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.0
zipp==3.8.1
```

**Comment by seanpearsonuk** [comment]
@mrf6166 please add a more specific description of what is not working / how the behaviour diverges from your expectations

**Comment by mrf6166** [comment]
Hi Sean,

Please see the attached:

[cid:3a4c0b79-c00c-49f5-b329-916ea374f47a]
when the production limiter is set as "True" the code, in the GUI/TUI, asks the user for the clip factor value, and you won't be able to run any other python command until you first set the value:

[cid:d6fb714e-1130-45a4-b95d-6a4e576808d7]
we didn't find anyway to set up the value using Python, it needs to be entered through TUI.

Also, to my best understanding, we are limited to adjust the model (here turbulence) to some degrees only such as below:
[cid:a1f41527-407b-4122-8208-5f11de6478ff]
is there any way we can use Python commands to adjust the model's constants?

[cid:c881d064-f5e7-48a1-ba7a-55655e83c20a]



Mohammadreza (Reza) Farokhi  /  Application Engineer II

[cid:3e5617d2-5fc4-4a4d-b9cd-7cf8ee3fa35a]
Waterloo ON, Canada  /  North America, East

Mobile # 204-590-8360 /  office #

***@***.******@***.***>  /   www.ansys.com<http://www.ansys.com/>
Sign-up<https://upl.inc/9dd4cb4> to receive e-mails from Ansys
________________________________

**Comment by seanpearsonuk** [comment]
Please try this
```
import ansys.fluent.core as pyfluent
session=pyfluent.launch_fluent(processor_count=2, show_gui=True, mode="solver")
session.file.read(file_type="case", file_name=<file_name>)
session.setup.models.viscous.model.allowed_values()
session.setup.models.viscous.model="k-epsilon"
session.setup.models.viscous.near_wall_treatment.wall_function="standard-wall-fn"
session.setup.models.viscous.options.curvature_correction=False
session.setup.models.viscous.turbulence_expert.production_limiter.enable_prod_limiter=True
```

**Comment by seanpearsonuk** [comment]
@dnwillia-work 
What do you see for `session.setup.models.viscous.model.allowed_values()`

**Comment by dnwillia-work** [comment]
OK, so it seems to be reproducible with 2022 R2, but I've verified that it's working properly with 2023 R1.  Thanks @seanpearsonuk
