### ISSUE TITLE
Setting API: Name error while defining cell zone conditions

### ISSUE THREAD

**Issue by akulshre-qa** [pyansys/pyfluent#837]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

We are getting name error when use:
solver.setup.cell_zone_conditions.fluid['fluid:substrate:1'] = {'material': 'hydrogen', 'dir_spec_cond': 'Conical'}

It gives the error as below:
Traceback (most recent call last):
  File "C:\Users\akulshre\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-256e481428ff>", line 1, in <cell line: 1>
    solver.setup.cell_zone_conditions.fluid['fluid:substrate:1'] = {'material': 'hydrogen', 'dir_spec_cond': 'Conical'}
  File "d:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 808, in __setitem__
    child.set_state(value)
  File "d:\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 239, in set_state
    return self.flproxy.set_var(self.path, self.to_scheme_keys(state))
  File "d:\pyfluent\src\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "d:\pyfluent\src\ansys\fluent\core\services\settings.py", line 148, in set_var
    self.__service_impl.set_var(request)
  File "d:\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: eval: unbound variable
Error Object: name

### 📝 Steps to reproduce

To reproduce:
- Run below commands:
```
import ansys.fluent.core as pyfluent
from util.solver import copy_database_material
from util.fixture_fluent import download_input_file
solver = pyfluent.launch_fluent(
        precision="double", processor_count=2, mode="solver"
    )
input_type, input_name = download_input_file("pyfluent/catalytic_converter", "catalytic_converter.msh.h5")
solver.file.read(file_type=input_type, file_name=input_name)
solver.execute_tui(r'''/define/units length mm ''')
solver.setup.models.energy = {"enabled": True, "inlet_diffusion": False}
copy_database_material(
	materials=solver.setup.materials, type="fluid", name="nitrogen"
)
copy_database_material(
	materials=solver.setup.materials, type="fluid", name="hydrogen"
)
solver.setup.cell_zone_conditions.fluid['fluid:0'] = {"material": "nitrogen"}
solver.execute_tui(r'''/define/boundary-conditions/copy-bc fluid:0 fluid:1 fluid:3 () ''')
solver.setup.cell_zone_conditions.fluid['fluid:substrate:1'] = {"material": "nitrogen", "porous": True}
solver.execute_tui(r'''/define/boundary-conditions/copy-bc fluid:substrate:1 fluid:substrate:2 () ''')
solver.setup.boundary_conditions.velocity_inlet['inlet'] = {"vmag": 125., "t": 800.,
															"ke_spec": "Intensity and Hydraulic Diameter",
															"turb_hydraulic_diam": 0.5}
solver.setup.boundary_conditions.pressure_outlet['outlet'] = {"t0": 800.,
															  "ke_spec": "Intensity and Hydraulic Diameter",
															  "turb_hydraulic_diam": 0.5}
solver.execute_tui(r'''/solve/initialize/compute-defaults/velocity-inlet inlet ''')
solver.solution.initialization.standard_initialize()
solver.solution.run_calculation.iter_count = 2
solver.solution.run_calculation.iterate(number_of_iterations=2)
solver.setup.cell_zone_conditions.fluid['fluid:substrate:1'] = {'material': 'hydrogen', 'dir_spec_cond': 'Conical'}
```
You will see errors at last line. 

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-platform-instancemanagement==1.0.2
ansys-sphinx-theme==0.4.2
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
atomicwrites==1.4.0
```

**Comment by seanpearsonuk** [comment]
@akulshre-qa   Please confirm that the issue is seen in PyFluent only and not in the Python console.

**Comment by seanpearsonuk** [comment]
Not reproducible locally with up-to-date versions of PyFluent and Fluent. Please reopen if still reproducible.
