### ISSUE TITLE
Unable to install the latest pyfluent from pypi

### ISSUE THREAD

**Issue by abhishekchitwar** [pyansys/pyfluent#838]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Unable to install the latest released version (Released: Sep 2, 2022)  from pypi.

### 📝 Steps to reproduce

1) Create environment by issuing following command in windows command line
    
    "C:\Program Files\ANSYS Inc\v231\commonfiles\CPython\3_7\winx64\Release\python\python.exe" -m venv "pyfluent_env"

2) Create the requirements.txt with following content 
     ansys-api-fluent
     ansys-fluent-visualization

3) Activate the environment using by issuing following command 
        pyfluent_env\Scripts\activate.bat

4) Install pyfluent using  following command 
        pip install -r requirements.txt

Error message for detailed reference;
![MicrosoftTeams-image](https://user-images.githubusercontent.com/99339845/188450607-015733c8-8c4a-4fb2-87f8-d137ff050c75.png)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
python -m pip freeze output

appdirs==1.4.4
backcall==0.2.0
pickleshare==0.7.5
Pygments==2.13.0
pyparsing==3.0.9
pytz==2022.2.1
pywin32==304
pyzmq==23.2.1
scooby==0.6.0
shiboken6==6.3.1
six==1.16.0
tornado==6.2
traitlets==5.3.0
typing_extensions==4.3.0
wcwidth==0.2.5
widgetsnbextension==4.0.3
zipp==3.8.1
```

**Comment by seanpearsonuk** [comment]
@ajain-work @mkundu1 
This seems to be the known issue for psutil in visualization.  Please confirm.

**Comment by seanpearsonuk** [comment]
dependency being removed in current version
@abhishekchitwar  also you can install in any python separate from ansys python

**Comment by abhishekchitwar** [comment]
Thanks Mainak, Sean, I'll try it!
