### ISSUE TITLE
Reading a case file leads to crash in fluent session

### ISSUE THREAD

**Issue by tejalprabhu01** [pyansys/pyfluent#846]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Unable to read attached case file. Getting the below error 
![image](https://user-images.githubusercontent.com/97435870/188612446-22d65186-bed4-4a02-bdc2-2d4aae20ce6a.png)
[Uploading Test_file.zip…]()

### 📝 Steps to reproduce
```
>>> session = pyfluent.launch_fluent()
>>> session.solver.tui.file.read_case(input_file)
```
### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
ansys-fluent-core
ansys-fluent-parametric
```

**Comment by seanpearsonuk** [comment]
@tejalprabhu01 

Not able to reproduce with latest versions of fluent and pyfluent

Please reopen if you still see an issue and we can discuss further

**Comment by seanpearsonuk** [comment]
We will need to check this again for any patch release.
