### ISSUE TITLE
TaskObject access syntax

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#853]
Current usage
```
workflow.TaskObject["Import Geometry"]
```
Want to simplify this since everything revolves around task objects.  How about:
```
workflow.Import%Geometry
```
Ta-da!

**Comment by h-krishnan** [comment]
Is the '%' a typo?

**Comment by seanpearsonuk** [comment]
It actually wasn't a typo, but it was based on fallacy that we could we use `__getattr__` to return intermediate objects with an overload of `__mod__` which would eventually return the task object. I didn't think it through all the way.

**Comment by seanpearsonuk** [comment]
Closing in favour of #1019
