### ISSUE TITLE
script to monitor flobject differences across two repos

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#871]
flobject.py exists in PyFluent and Fluent git repos. Shall we write a script to periodically check for differences between the two files?

**Comment by hpohekar** [comment]
@seanpearsonuk we can use filecmp or difflib built-in modules from python to compare 2 files.

**Comment by hpohekar** [comment]
Hi @seanpearsonuk , The required script is already created by @mkundu1 and it's working fine. 

https://github.com/pyansys/pyfluent/actions/workflows/compare-flobject.yml
