### ISSUE TITLE
Fluent Lite Mode

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#888]
Improvements around introduction of lightweight mode. Add infrastructure to allow interaction with a lightweight server while a heavyweight server is being launched in the background. Seamlessly switch to the heavyweight server when initialised.

**Comment by seanpearsonuk** [comment]
@prmukherj @hpohekar @mkundu 

just added this to prioritized

**Comment by mkundu1** [comment]
Changes added
