### ISSUE TITLE
-gu mode not working in pyfluent

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#893]
```
import ansys.fluent.core as pf
s = pf.launch_fluent(additional_arguments="-gu")
s.check_health()
s.solver.root.setup
```
This causes a hang. If I try to execute a remote call, there is an error due to call to cx-version in Fluent - I have checked that I can call that function in Fluent directly when running with -gu. -g I see same issue.

**Comment by seanpearsonuk** [comment]
Could be a generic issue with additional_arguments.  e.g. -py reported not working by @hpohekar

**Comment by prmukherj** [comment]
@mkundu1, commented:
The issue related to additional_arguments=-gu, is due to known limitation of Fluent server mode in Windows (-gu is not supported in windows in Fluent server). It works in Linux without any issues. Also, additional_arguments is generally working for me.
