### ISSUE TITLE
add arguments method for solver command objects

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#908]
Implement in terms of command.get_attr("arguments")

**Comment by hpohekar** [comment]
Hi @seanpearsonuk , it's already implemented. Following is from `mixing_elbow_settings_api.py`

![image](https://user-images.githubusercontent.com/106588300/193201017-a8e7189d-1120-403a-834a-c6d0d7e9e044.png)

**Comment by hpohekar** [comment]
Hi @seanpearsonuk We don't have implementation of `iterate.arguments()`.

![image](https://user-images.githubusercontent.com/106588300/193270510-38ed3812-d77c-4aad-833c-8389a596ecab.png)
