### ISSUE TITLE
Settings API Attribute error when we try to get default value

### ISSUE THREAD

**Issue by akulshre-qa** [pyansys/pyfluent#923]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Below method doesn't work:
solver_session.setup.general.solver.type.default_value()
{AttributeError}'NoneType' object has no attribute 'get'

It works fine with Fluent build from 18 Sep and broken sometime after that. 

### 📝 Steps to reproduce

Run test_general test to see the issue. 

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
ansys-api-fluent==0.3.0
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pyfluent.git@2627f629cfa316ac6e412da102a5fcd827a6a312#egg=ansys_fluent_core
-e git+https://github.com/pyansys/pyfluent-parametric.git@06340964a758ed4c4b98c827f7db663bf8d36462#egg=ansys_fluent_parametric
ansys-fluent-solver==0.8.dev0
-e git+https://github.com/pyansys/pyfluent-ui@dc620f820b3cf786e5ad09826a4eb97dc0e9d0ad#egg=ansys_fluent_ui
-e git+https://github.com/pyansys/pyfluent-visualization.git@96a4967c503bbcd51bad62f9a8d7cf5210de5d06#egg=ansys_fluent_visualization
ansys-platform-instancemanagement==1.0.2
ansys-sphinx-theme==0.4.2
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
async-timeout==4.0.2
atomicwrites==1.4.0
```

**Comment by akulshre-qa** [comment]
@mkundu1 @prmukherj FYI

**Comment by prmukherj** [comment]
@akulshre-qa , @mkundu1 I am not facing this issue with the latest build of fluent.
"Build Time: Sep 22 2022 16:50:05 EDT  Build Id: 164  Revision: 6771b4240c  Branch: develop"

However, the test will fail with assertion error as the default_value() is returning None. That needs to be updated.

**Comment by akulshre-qa** [comment]
My Fluent build is Build Time: Sep 20 2022 05:33:35 EDT  Build Id: 162  Revision: 9ca8570293  Branch: develop

In nightly CI both the tests are failing currently due to the mentioned issue. Will check with latest build once it is available. I however believe that the default value should not return None for solver type.
