### ISSUE TITLE
Add doc style check in precommit

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#931]
doc style check, via vale, can fail in github, but isn't incorporated in the precommit via the dedicated config file. Is it possible to add it? Can we do this in all repos as appropriate?

**Comment by hpohekar** [comment]
Hi @seanpearsonuk I discussed this issue with @mkundu1 and we found that vale is not officially supported by pre-commit yet.

Here is the list of hooks supported by pre-commit. - https://pre-commit.com/hooks.html

We have also found some other ways related to vale on following links -

Installation - 
https://vale.sh/docs/vale-cli/installation/

Configuration -
https://vale.sh/generator/

Quick start -
https://vale.sh/docs/vale-cli/structure/#quick-start

**Comment by seanpearsonuk** [comment]
Thanks, @hpohekar, @mkundu1. I will close this now.
