### ISSUE TITLE
arbitrary variation in argument names in FieldData class

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#936]
```
    def get_vector_field_data(
          self,
          surface_name: str,
          vector_field: Optional[str]...

    def get_scalar_field_data(
        self,
        surface_name: str,
        field_name: str...
```
get_vector_field_data has field_name, get_vector_field_data has vector_field.

**Comment by prmukherj** [comment]
@seanpearsonuk, similar inconsistency was also observed in "add_get_vector_fields_request()" and the same has also been addressed. Thank you
