### ISSUE TITLE
PyFluent: Fluent requires users input to proceed when started in the -g mode (or "-gu -driver null" mode).

### ISSUE THREAD

**Issue by ypatel-qa** [pyansys/pyfluent#967]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Fluent requires users input to proceed when started in the -g mode (or "-gu -driver null" mode)

### 📝 Steps to reproduce

I am using the latest R23.1. I am testing on Windows using venv created with Ansys CPython. 

To reproduce: Run attached script. ("c:\shared\pyfluent\Scripts\python.exe" script.py)

[files.zip](https://github.com/pyansys/pyfluent/files/9701716/files.zip)

Fluent is hanging after every step (unless user provide some input, or hit the return key). Also cx2310.exe windows is showing up, which probably should not. 

![image](https://user-images.githubusercontent.com/97630098/193703864-52f0da65-974b-47cd-bdd9-381fc80def7d.png)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.1
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pyfluent.git@42e8194b3a4a9dd76d5617d0d6a8476ea4284aee#egg=ansys_fluent_core
ansys-platform-instancemanagement==1.0.2
appdirs==1.4.4
googleapis-common-protos==1.56.4
grpcio==1.49.1
h5py==3.7.0
importlib-metadata==5.0.0
numpy==1.21.6
packaging==21.3
pandas==1.3.5
Pint==0.18
protobuf==3.20.2
protoc-gen-swagger==0.1.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.4
six==1.16.0
typing_extensions==4.3.0
zipp==3.8.1
```

**Comment by dnwillia-work** [comment]
@mkundu1 @seanpearsonuk  Any diea if this one requires changes on the Fluent side?

**Comment by mkundu1** [comment]
@dnwillia-work @seanpearsonuk @ypatel-qa This is due to limitation of Fluent's grpc server - it doesn't work with -g/-gu mode in windows (point 3 of https://ansysproducthelpqa.win.ansys.com/account/secured?returnurl=/Views/Secured/corp/v231/en/flu_ug/flu_ug_remote-client_limitations.html)

**Comment by dnwillia-work** [comment]
I can't see that link, it's internal to Ansys.  Probably that should be documented for PyFluent then too and maybe we filter out the options (i.e. ignore them) on windows?

**Comment by seanpearsonuk** [comment]
@dnwillia-work, assigning to @hpohekar to constrain the launch options on Windows. If -g or -gu appears in the launch arguments on Windows, we can raise an exception.

@mkundu1, I think I should also open a Fluent defect for the server issue.
