### ISSUE TITLE
Bug when Creating External Flow Boundaries with Box Parameters

### ISSUE THREAD

**Issue by DavidAssad** [pyansys/pyfluent#976]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While using the Fault-Tolerant Mesh Workflow in the Fluent meshing mode, an error occurs after executing the created external flow boundaries. I am able to verify in the gui window that the fields are filled properly. However, the error pops up when hitting the execute command.
The code used for that TaskObject:
`>>> meshing.workflow.TaskObject["Create External Flow Boundaries"].Arguments.setState({"BoundingBoxObject": { "SizeRelativeLength": "Directly specify coordinates", "Xmax": 10600, "Xmin": -10000, "Ymax": 6000, "Ymin": 0, "Zmax": 3400,"Zmin": -3000,}, "CreationMethod": "Create new boundary", "ExternalBoundariesName": "Fluiddomain", "ExtractionMethod":"wrap",})`
`>>> meshing.workflow.TaskObject['Create External Flow Boundaries'].Execute()`

Error:
```
Error: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f 
```
Other tests/investigation: 
- The same commands above worked directly in the meshing worklfow/gui.
- Another test where all the commands were done in the meshing workflow except the execute command which was done in the command console. The enclosure was then successfully created. 

### 📝 Steps to reproduce

Commands used:
1) `import ansys.fluent.core as pyfluent`
2) `import_filename = 'FILENAME'`
3) `meshing = pyfluent.launch_fluent(precision="double", processor_count=2, show_gui=True, mode="meshing")` #Launching Meshing Mode
4) `meshing.PartManagement.InputFileChanged( FilePath = 'FILEPATH', IgnoreSolidNames=False, PartPerBody=False)` #Importing Geometry
5) `meshing.PMFileManagement.FileManager.LoadFiles() `
6) `meshing.workflow.TaskObject["Import CAD and Part Management"].Execute()`
7) `meshing.workflow.TaskObject["Describe Geometry and Flow"].Arguments.setState({"AddEnclosure": "Yes", "CloseCaps": "No", "FlowType": "External flow around object",})` #Specifying Flow Type
8) `meshing.workflow.TaskObject["Describe Geometry and Flow"].Execute()`
9) `meshing.workflow.TaskObject["Create External Flow Boundaries"].Arguments.setState({"BoundingBoxObject": { "SizeRelativeLength": "Directly specify coordinates", "Xmax": 10600, "Xmin": -10000, "Ymax": 6000, "Ymin": 0, "Zmax": 3400,"Zmin": -3000,}, "CreationMethod": "Create new boundary", "ExternalBoundariesName": "Fluiddomain", "ExtractionMethod":"wrap",})` #Specifying Enclosure
10) `meshing.workflow.TaskObject['Create External Flow Boundaries'].Execute()`
11) Error occurs after executing step 10.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
aiohttp==3.8.3
aiosignal==1.2.0
ansys-api-fluent==0.3.1
ansys-api-mapdl==0.5.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-corba==0.1.1
ansys-dpf-core==0.6.dev0
ansys-dpf-gate==0.2.1
ansys-dpf-gatebin==0.2.1
ansys-dpf-post==0.2.5
ansys-fluent-core==0.11.0
ansys-grpc-dpf==0.6.0
ansys-mapdl-core==0.63.2
ansys-mapdl-reader==0.52.0
ansys-platform-instancemanagement==1.0.2
ansys-systemcoupling-core @ file:///C:/Users/dassad/ansys_systemcoupling_core-0.1.dev0-py3-none-any.whl
appdirs==1.4.4
async-timeout==4.0.2
attrs==22.1.0
cachetools==5.2.0
certifi==2022.9.14
charset-normalizer==2.1.1
colorama==0.4.5
contourpy==1.0.5
cycler==0.11.0
fonttools==4.37.3
frozenlist==1.3.1
geomdl==5.3.1
google-api-core==2.10.1
google-api-python-client==2.62.0
google-auth==2.11.1
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.4
grpcio==1.49.1
grpcio-status==1.48.2
h5py==3.7.0
httplib2==0.20.4
idna==3.4
imageio==2.22.0
importlib-metadata==4.12.0
kiwisolver==1.4.4
matplotlib==3.6.0
multidict==6.0.2
numpy==1.23.3
packaging==21.3
pandas==1.5.0
Pillow==9.2.0
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil==5.9.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyiges==0.2.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.2.1
pyvista==0.36.1
PyYAML==6.0
requests==2.28.1
rsa==4.9
scipy==1.9.1
scooby==0.6.0
six==1.16.0
tqdm==4.64.1
uritemplate==4.1.1
urllib3==1.26.12
vtk==9.1.0
wslink==1.8.2
yarl==1.8.1
zipp==3.8.1
```

**Comment by seanpearsonuk** [comment]
@DavidAssad what files is this loading?

**Comment by DavidAssad** [comment]
> @DavidAssad what files is this loading?

This is loading a spaceclaim geometry file.

**Comment by seanpearsonuk** [comment]
Hi @DavidAssad are you using Ansys 2022R2 or 2023R1 or both (same outcome)? Thanks

**Comment by DavidAssad** [comment]
Hey @seanpearsonuk 
I am using Ansys 2023R1.

**Comment by DavidAssad** [comment]
> Hi @DavidAssad are you using Ansys 2022R2 or 2023R1 or both (same outcome)? Thanks

Hey,
I am using Ansys 2023R1

**Comment by seanpearsonuk** [comment]
Following error is observed when running this directly without PyFluent (e.g., first execute `(%py-console)` in meshing workflow).

```
Error: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f
```
