### ISSUE TITLE
Some pages are broken in dev docs

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#977]
Compare https://dev.fluent.docs.pyansys.com/api/core/solver/settings.html with https://fluent.docs.pyansys.com/api/core/solver/settings.html. If you scroll the issue is clear. This doesn't look good.

**Comment by dnwillia-work** [comment]
Do you mean that the style is a bit different.  eg: the release doc uses different colors for the emphasized objects/methods.

**Comment by seanpearsonuk** [comment]
> Do you mean that the style is a bit different? eg: the release doc uses different colors for the emphasized objects/methods.
> 
> I see the content is different/updated in the development version, which is fine.

At the time of raising the issue I was seeing the table of contents rendering messed up. I was actually looking at it today and it looked fine, so that might have been a temporary glitch or browser issue. Let me monitor before closing.

**Comment by dnwillia-work** [comment]
OK, cool.  One reason for differences can be the differences in upgraded requirements.  For instance:

https://github.com/pyansys/pyfluent/blob/main/requirements/requirements_doc.txt
https://github.com/pyansys/pyfluent/blob/release/0.11/requirements/requirements_doc.txt

On `main` we've upgraded Sphinx version, Ansys theme version, etc...

**Comment by dnwillia-work** [comment]
I guess we can close this one then since it seems to have been a glitch.
